// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package files represents the imported interface "nib:plugin/files@0.7.3".
//
// File lists, for plugins with the "fs-read" capability. The files are
// counted on a background thread, so plugins never wait for them.
package files

import (
	"go.bytecodealliance.org/cm"
)

// DirEntry represents the record "nib:plugin/files@0.7.3#dir-entry".
//
//	record dir-entry {
//		name: string,
//		directory: bool,
//		size: u64,
//		mode: option<u32>,
//		modified: option<u64>,
//	}
type DirEntry struct {
	_    cm.HostLayout `json:"-"`
	Name string        `json:"name"`

	// A directory, or a link to one.
	Directory bool `json:"directory"`

	// In bytes; 0 for a directory.
	Size uint64 `json:"size"`

	// The Unix permission bits, such as 0o755; none elsewhere.
	Mode cm.Option[uint32] `json:"mode"`

	// When it last changed, in seconds since 1970.
	Modified cm.Option[uint64] `json:"modified"`
}

// WalkOptions represents the record "nib:plugin/files@0.7.3#walk-options".
//
//	record walk-options {
//		hidden: bool,
//		ignored: bool,
//	}
type WalkOptions struct {
	_ cm.HostLayout `json:"-"`
	// Hidden files and directories too.
	Hidden bool `json:"hidden"`

	// What .gitignore and the like leave out too.
	Ignored bool `json:"ignored"`
}

// List represents the imported function "list".
//
// What `dir` holds, hidden files too, sorted by name: one level, not
// the files under it. Needs the "fs-read" capability.
//
//	%list: func(dir: string) -> result<list<dir-entry>, string>
//
//go:nosplit
func List(dir string) (result cm.Result[cm.List[DirEntry], cm.List[DirEntry], string]) {
	dir0, dir1 := cm.LowerString(dir)
	wasmimport_List((*uint8)(dir0), (uint32)(dir1), &result)
	return
}

// Walk represents the imported function "walk".
//
// Lists the files under `dir`, or the working directory, honoring
// .gitignore and leaving out hidden files. The paths arrive as
// `files-listed` events, relative to `dir` and with `/` between names.
// Returns the job's id.
//
//	walk: func(dir: option<string>) -> result<u64, string>
//
//go:nosplit
func Walk(dir cm.Option[string]) (result cm.Result[string, uint64, string]) {
	dir0, dir1, dir2 := lower_OptionString(dir)
	wasmimport_Walk((uint32)(dir0), (*uint8)(dir1), (uint32)(dir2), &result)
	return
}

// WalkWith represents the imported function "walk-with".
//
// As `walk`, with hidden files and ignored ones when asked.
//
//	walk-with: func(dir: option<string>, options: walk-options) -> result<u64, string>
//
//go:nosplit
func WalkWith(dir cm.Option[string], options WalkOptions) (result cm.Result[string, uint64, string]) {
	dir0, dir1, dir2 := lower_OptionString(dir)
	options0, options1 := lower_WalkOptions(options)
	wasmimport_WalkWith((uint32)(dir0), (*uint8)(dir1), (uint32)(dir2), (uint32)(options0), (uint32)(options1), &result)
	return
}

// MakeDir represents the imported function "make-dir".
//
// Makes a directory, and those above it that are missing. Needs the
// "fs-write" capability.
//
//	make-dir: func(path: string) -> result<_, string>
//
//go:nosplit
func MakeDir(path string) (result cm.Result[string, struct{}, string]) {
	path0, path1 := cm.LowerString(path)
	wasmimport_MakeDir((*uint8)(path0), (uint32)(path1), &result)
	return
}

// Cancel represents the imported function "cancel".
//
// Stops a job; nothing more arrives from it.
//
//	cancel: func(id: u64)
//
//go:nosplit
func Cancel(id uint64) {
	id0 := (uint64)(id)
	wasmimport_Cancel((uint64)(id0))
	return
}
