// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package files represents the imported interface "nib:plugin/files@0.7.0".
//
// File lists, for plugins with the "fs-read" capability. The files are
// counted on a background thread, so plugins never wait for them.
package files

import (
	"go.bytecodealliance.org/cm"
)

// Walk represents the imported function "walk".
//
// Lists the files under `dir`, or the working directory, honoring
// .gitignore and leaving out hidden files. The paths arrive as
// `files-listed` events, relative to `dir` and with `/` between names.
// Returns the job's id.
//
//	walk: func(dir: option<string>) -> result<u64, string>
//
//go:nosplit
func Walk(dir cm.Option[string]) (result cm.Result[string, uint64, string]) {
	dir0, dir1, dir2 := lower_OptionString(dir)
	wasmimport_Walk((uint32)(dir0), (*uint8)(dir1), (uint32)(dir2), &result)
	return
}

// Cancel represents the imported function "cancel".
//
// Stops a job; nothing more arrives from it.
//
//	cancel: func(id: u64)
//
//go:nosplit
func Cancel(id uint64) {
	id0 := (uint64)(id)
	wasmimport_Cancel((uint64)(id0))
	return
}
