// Code generated by wit-bindgen-go. DO NOT EDIT.

package files

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.7.2".

//go:wasmimport nib:plugin/files@0.7.2 list
//go:noescape
func wasmimport_List(dir0 *uint8, dir1 uint32, result *cm.Result[cm.List[DirEntry], cm.List[DirEntry], string])

//go:wasmimport nib:plugin/files@0.7.2 walk
//go:noescape
func wasmimport_Walk(dir0 uint32, dir1 *uint8, dir2 uint32, result *cm.Result[string, uint64, string])

//go:wasmimport nib:plugin/files@0.7.2 cancel
//go:noescape
func wasmimport_Cancel(id0 uint64)
