// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package ui represents the imported interface "nib:plugin/ui@0.7.2".
package ui

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/buffer"
	"github.com/nib-editor/nib/sdk/go/nib/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Offset represents the type alias "nib:plugin/ui@0.7.2#offset".
//
// See [types.Offset] for more information.
type Offset = types.Offset

// StyledLine represents the type alias "nib:plugin/ui@0.7.2#styled-line".
//
// See [types.StyledLine] for more information.
type StyledLine = types.StyledLine

// Buffer represents the imported type alias "nib:plugin/ui@0.7.2#buffer".
//
// See [buffer.Buffer] for more information.
type Buffer = buffer.Buffer

// Side represents the enum "nib:plugin/ui@0.7.2#side".
//
//	enum side {
//		left,
//		right
//	}
type Side uint8

const (
	SideLeft Side = iota
	SideRight
)

var _SideStrings = [2]string{
	"left",
	"right",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Side) String() string {
	return _SideStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Side) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Side) UnmarshalText(text []byte) error {
	return _SideUnmarshalCase(e, text)
}

var _SideUnmarshalCase = cm.CaseUnmarshaler[Side](_SideStrings[:])

// Panel represents the imported resource "nib:plugin/ui@0.7.2#panel".
//
// Lines at the bottom of the screen, above the status line. Dropping the
// panel closes it.
//
//	resource panel
type Panel cm.Resource

// ResourceDrop represents the imported resource-drop for resource "panel".
//
// Drops a resource handle.
//
//go:nosplit
func (self Panel) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PanelResourceDrop((uint32)(self0))
	return
}

// NewPanel represents the imported constructor for resource "panel".
//
//	constructor(lines: list<styled-line>)
//
//go:nosplit
func NewPanel(lines cm.List[StyledLine]) (result Panel) {
	lines0, lines1 := cm.LowerList(lines)
	result0 := wasmimport_NewPanel((*StyledLine)(lines0), (uint32)(lines1))
	result = cm.Reinterpret[Panel]((uint32)(result0))
	return
}

// SetCursor represents the imported method "set-cursor".
//
// A line index and a byte offset into that line's text. While set,
// the cursor is drawn there instead of in the buffer.
//
//	set-cursor: func(cursor: option<tuple<u32, u32>>)
//
//go:nosplit
func (self Panel) SetCursor(cursor cm.Option[[2]uint32]) {
	self0 := cm.Reinterpret[uint32](self)
	cursor0, cursor1, cursor2 := lower_OptionTupleU32U32(cursor)
	wasmimport_PanelSetCursor((uint32)(self0), (uint32)(cursor0), (uint32)(cursor1), (uint32)(cursor2))
	return
}

// Update represents the imported method "update".
//
//	update: func(lines: list<styled-line>)
//
//go:nosplit
func (self Panel) Update(lines cm.List[StyledLine]) {
	self0 := cm.Reinterpret[uint32](self)
	lines0, lines1 := cm.LowerList(lines)
	wasmimport_PanelUpdate((uint32)(self0), (*StyledLine)(lines0), (uint32)(lines1))
	return
}

// PopupAnchor represents the variant "nib:plugin/ui@0.7.2#popup-anchor".
//
//	variant popup-anchor {
//		position(offset),
//		corner,
//	}
type PopupAnchor cm.Variant[uint8, Offset, Offset]

// PopupAnchorPosition returns a [PopupAnchor] of case "position".
//
// Below the line of this offset in the shown buffer, or above it
// when there is no room. Hidden while the offset is off screen.
// The offset does not follow edits: open a new popup to move it.
func PopupAnchorPosition(data Offset) PopupAnchor {
	return cm.New[PopupAnchor](0, data)
}

// Position returns a non-nil *[Offset] if [PopupAnchor] represents the variant case "position".
func (self *PopupAnchor) Position() *Offset {
	return cm.Case[Offset](self, 0)
}

// PopupAnchorCorner returns a [PopupAnchor] of case "corner".
//
// The bottom-right corner of the text, e.g. for key hints.
func PopupAnchorCorner() PopupAnchor {
	var data struct{}
	return cm.New[PopupAnchor](1, data)
}

// Corner returns true if [PopupAnchor] represents the variant case "corner".
func (self *PopupAnchor) Corner() bool {
	return self.Tag() == 1
}

var _PopupAnchorStrings = [2]string{
	"position",
	"corner",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v PopupAnchor) String() string {
	return _PopupAnchorStrings[v.Tag()]
}

// Popup represents the imported resource "nib:plugin/ui@0.7.2#popup".
//
// Lines drawn over the text. They never take the cursor. Dropping the
// popup closes it.
//
//	resource popup
type Popup cm.Resource

// ResourceDrop represents the imported resource-drop for resource "popup".
//
// Drops a resource handle.
//
//go:nosplit
func (self Popup) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PopupResourceDrop((uint32)(self0))
	return
}

// NewPopup represents the imported constructor for resource "popup".
//
//	constructor(anchor: popup-anchor, lines: list<styled-line>)
//
//go:nosplit
func NewPopup(anchor PopupAnchor, lines cm.List[StyledLine]) (result Popup) {
	anchor0, anchor1 := lower_PopupAnchor(anchor)
	lines0, lines1 := cm.LowerList(lines)
	result0 := wasmimport_NewPopup((uint32)(anchor0), (uint64)(anchor1), (*StyledLine)(lines0), (uint32)(lines1))
	result = cm.Reinterpret[Popup]((uint32)(result0))
	return
}

// Update represents the imported method "update".
//
//	update: func(lines: list<styled-line>)
//
//go:nosplit
func (self Popup) Update(lines cm.List[StyledLine]) {
	self0 := cm.Reinterpret[uint32](self)
	lines0, lines1 := cm.LowerList(lines)
	wasmimport_PopupUpdate((uint32)(self0), (*StyledLine)(lines0), (uint32)(lines1))
	return
}

// Decoration represents the record "nib:plugin/ui@0.7.2#decoration".
//
// A style over `start..end` of a buffer, drawn over the syntax
// highlighting and under the selection. It only sets what the style
// sets, e.g. the text color.
//
//	record decoration {
//		start: offset,
//		end: offset,
//		style: string,
//	}
type Decoration struct {
	_     cm.HostLayout `json:"-"`
	Start Offset        `json:"start"`
	End   Offset        `json:"end"`
	Style string        `json:"style"`
}

// Note represents the record "nib:plugin/ui@0.7.2#note".
//
// Text shown after the end of the line of `at`, such as a diagnostic's
// message.
//
//	record note {
//		at: offset,
//		text: string,
//		style: string,
//	}
type Note struct {
	_     cm.HostLayout `json:"-"`
	At    Offset        `json:"at"`
	Text  string        `json:"text"`
	Style string        `json:"style"`
}

// SetStatus represents the imported function "set-status".
//
// Shows an item in the status line, replacing this plugin's item with
// the same `id`. Items on one side are ordered by `priority`, lowest
// first.
//
//	set-status: func(id: string, side: side, priority: s32, content: styled-line)
//
//go:nosplit
func SetStatus(id string, side Side, priority int32, content StyledLine) {
	id0, id1 := cm.LowerString(id)
	side0 := (uint32)(side)
	priority0 := (uint32)(priority)
	content0, content1 := cm.LowerList(content)
	wasmimport_SetStatus((*uint8)(id0), (uint32)(id1), (uint32)(side0), (uint32)(priority0), (*types.Span)(content0), (uint32)(content1))
	return
}

// RemoveStatus represents the imported function "remove-status".
//
//	remove-status: func(id: string)
//
//go:nosplit
func RemoveStatus(id string) {
	id0, id1 := cm.LowerString(id)
	wasmimport_RemoveStatus((*uint8)(id0), (uint32)(id1))
	return
}

// ShowMessage represents the imported function "show-message".
//
// Shows a message until the next key.
//
//	show-message: func(text: string)
//
//go:nosplit
func ShowMessage(text string) {
	text0, text1 := cm.LowerString(text)
	wasmimport_ShowMessage((*uint8)(text0), (uint32)(text1))
	return
}

// SetDecorations represents the imported function "set-decorations".
//
// Replaces this plugin's decorations in `namespace` on `buf`; an empty
// list removes them. The core moves them with later edits, and drops
// ones whose text is deleted. Ranges are cut to the buffer.
//
//	set-decorations: func(buf: borrow<buffer>, namespace: string, decorations: list<decoration>)
//
//go:nosplit
func SetDecorations(buf Buffer, namespace string, decorations cm.List[Decoration]) {
	buf0 := cm.Reinterpret[uint32](buf)
	namespace0, namespace1 := cm.LowerString(namespace)
	decorations0, decorations1 := cm.LowerList(decorations)
	wasmimport_SetDecorations((uint32)(buf0), (*uint8)(namespace0), (uint32)(namespace1), (*Decoration)(decorations0), (uint32)(decorations1))
	return
}

// SetNotes represents the imported function "set-notes".
//
// Replaces this plugin's notes in `namespace` on `buf`, as with
// decorations. Notes move with edits and stay when the text around
// them is deleted.
//
//	set-notes: func(buf: borrow<buffer>, namespace: string, notes: list<note>)
//
//go:nosplit
func SetNotes(buf Buffer, namespace string, notes cm.List[Note]) {
	buf0 := cm.Reinterpret[uint32](buf)
	namespace0, namespace1 := cm.LowerString(namespace)
	notes0, notes1 := cm.LowerList(notes)
	wasmimport_SetNotes((uint32)(buf0), (*uint8)(namespace0), (uint32)(namespace1), (*Note)(notes0), (uint32)(notes1))
	return
}
