// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package commands represents the imported interface "nib:plugin/commands@0.7.3".
package commands

import (
	"go.bytecodealliance.org/cm"
)

// Register represents the imported function "register".
//
// Registers the command `<plugin>.<name>`, where `<plugin>` is this
// plugin's name. Calls reach this plugin's `run-command` with `name`.
// Registering a name again replaces its description.
//
//	register: func(name: string, description: string)
//
//go:nosplit
func Register(name string, description string) {
	name0, name1 := cm.LowerString(name)
	description0, description1 := cm.LowerString(description)
	wasmimport_Register((*uint8)(name0), (uint32)(name1), (*uint8)(description0), (uint32)(description1))
	return
}

// Call represents the imported function "call".
//
// Runs a command by its full name and waits for its result. Arguments
// and the result are JSON; empty arguments are `{}`. Calling a plugin
// that is already in a call, such as the caller itself, is an error.
// The core's commands, such as `buffer.save`, call the functions of
// this API by name, for keys and command lines.
//
//	call: func(name: string, args: string) -> result<string, string>
//
//go:nosplit
func Call(name string, args string) (result cm.Result[string, string, string]) {
	name0, name1 := cm.LowerString(name)
	args0, args1 := cm.LowerString(args)
	wasmimport_Call((*uint8)(name0), (uint32)(name1), (*uint8)(args0), (uint32)(args1), &result)
	return
}

// All represents the imported function "all".
//
// Every command, core and registered, with its description.
//
//	all: func() -> list<tuple<string, string>>
//
//go:nosplit
func All() (result cm.List[[2]string]) {
	wasmimport_All(&result)
	return
}
