// Code generated by wit-bindgen-go. DO NOT EDIT.

package commands

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.5.3".

//go:wasmimport nib:plugin/commands@0.5.3 register
//go:noescape
func wasmimport_Register(name0 *uint8, name1 uint32, description0 *uint8, description1 uint32)

//go:wasmimport nib:plugin/commands@0.5.3 call
//go:noescape
func wasmimport_Call(name0 *uint8, name1 uint32, args0 *uint8, args1 uint32, result *cm.Result[string, string, string])

//go:wasmimport nib:plugin/commands@0.5.3 all
//go:noescape
func wasmimport_All(result *cm.List[[2]string])
