// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package view represents the imported interface "nib:plugin/view@0.7.2".
package view

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/buffer"
	"github.com/nib-editor/nib/sdk/go/nib/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Offset represents the type alias "nib:plugin/view@0.7.2#offset".
//
// See [types.Offset] for more information.
type Offset = types.Offset

// Range represents the type alias "nib:plugin/view@0.7.2#range".
//
// See [types.Range] for more information.
type Range = types.Range

// Selection represents the type alias "nib:plugin/view@0.7.2#selection".
//
// See [types.Selection] for more information.
type Selection = types.Selection

// Edit represents the type alias "nib:plugin/view@0.7.2#edit".
//
// See [types.Edit] for more information.
type Edit = types.Edit

// UndoMode represents the type alias "nib:plugin/view@0.7.2#undo-mode".
//
// See [types.UndoMode] for more information.
type UndoMode = types.UndoMode

// CursorShape represents the type alias "nib:plugin/view@0.7.2#cursor-shape".
//
// See [types.CursorShape] for more information.
type CursorShape = types.CursorShape

// Error represents the type alias "nib:plugin/view@0.7.2#error".
//
// See [types.Error] for more information.
type Error = types.Error

// Buffer represents the imported type alias "nib:plugin/view@0.7.2#buffer".
//
// See [buffer.Buffer] for more information.
type Buffer = buffer.Buffer

// ScrollAmount represents the variant "nib:plugin/view@0.7.2#scroll-amount".
//
//	variant scroll-amount {
//		lines(s32),
//		half-page(s32),
//		page(s32),
//	}
type ScrollAmount cm.Variant[uint8, int32, int32]

// ScrollAmountLines returns a [ScrollAmount] of case "lines".
func ScrollAmountLines(data int32) ScrollAmount {
	return cm.New[ScrollAmount](0, data)
}

// Lines returns a non-nil *[int32] if [ScrollAmount] represents the variant case "lines".
func (self *ScrollAmount) Lines() *int32 {
	return cm.Case[int32](self, 0)
}

// ScrollAmountHalfPage returns a [ScrollAmount] of case "half-page".
func ScrollAmountHalfPage(data int32) ScrollAmount {
	return cm.New[ScrollAmount](1, data)
}

// HalfPage returns a non-nil *[int32] if [ScrollAmount] represents the variant case "half-page".
func (self *ScrollAmount) HalfPage() *int32 {
	return cm.Case[int32](self, 1)
}

// ScrollAmountPage returns a [ScrollAmount] of case "page".
func ScrollAmountPage(data int32) ScrollAmount {
	return cm.New[ScrollAmount](2, data)
}

// Page returns a non-nil *[int32] if [ScrollAmount] represents the variant case "page".
func (self *ScrollAmount) Page() *int32 {
	return cm.Case[int32](self, 2)
}

var _ScrollAmountStrings = [3]string{
	"lines",
	"half-page",
	"page",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v ScrollAmount) String() string {
	return _ScrollAmountStrings[v.Tag()]
}

// Direction represents the enum "nib:plugin/view@0.7.2#direction".
//
//	enum direction {
//		vertical,
//		horizontal
//	}
type Direction uint8

const (
	DirectionVertical Direction = iota
	DirectionHorizontal
)

var _DirectionStrings = [2]string{
	"vertical",
	"horizontal",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Direction) String() string {
	return _DirectionStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Direction) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Direction) UnmarshalText(text []byte) error {
	return _DirectionUnmarshalCase(e, text)
}

var _DirectionUnmarshalCase = cm.CaseUnmarshaler[Direction](_DirectionStrings[:])

// Toward represents the enum "nib:plugin/view@0.7.2#toward".
//
//	enum toward {
//		next,
//		left,
//		right,
//		up,
//		down
//	}
type Toward uint8

const (
	TowardNext Toward = iota
	TowardLeft
	TowardRight
	TowardUp
	TowardDown
)

var _TowardStrings = [5]string{
	"next",
	"left",
	"right",
	"up",
	"down",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Toward) String() string {
	return _TowardStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Toward) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Toward) UnmarshalText(text []byte) error {
	return _TowardUnmarshalCase(e, text)
}

var _TowardUnmarshalCase = cm.CaseUnmarshaler[Toward](_TowardStrings[:])

// View represents the imported resource "nib:plugin/view@0.7.2#view".
//
// The focused view.
//
//	resource view
type View cm.Resource

// ResourceDrop represents the imported resource-drop for resource "view".
//
// Drops a resource handle.
//
//go:nosplit
func (self View) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewResourceDrop((uint32)(self0))
	return
}

// Apply represents the imported method "apply".
//
// Applies `edits` atomically. Without `after`, the selection is
// mapped through the change.
//
//	apply: func(base-version: u64, edits: list<edit>, after: option<selection>, undo:
//	undo-mode) -> result<_, error>
//
//go:nosplit
func (self View) Apply(baseVersion uint64, edits cm.List[Edit], after cm.Option[Selection], undo UndoMode) (result cm.Result[Error, struct{}, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	baseVersion0 := (uint64)(baseVersion)
	edits0, edits1 := cm.LowerList(edits)
	after0, after1, after2, after3 := lower_OptionSelection(after)
	undo0 := (uint32)(undo)
	wasmimport_ViewApply((uint32)(self0), (uint64)(baseVersion0), (*Edit)(edits0), (uint32)(edits1), (uint32)(after0), (*types.SelRange)(after1), (uint32)(after2), (uint32)(after3), (uint32)(undo0), &result)
	return
}

// Buffer represents the imported method "buffer".
//
//	buffer: func() -> buffer
//
//go:nosplit
func (self View) Buffer() (result Buffer) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ViewBuffer((uint32)(self0))
	result = cm.Reinterpret[Buffer]((uint32)(result0))
	return
}

// MoveVertically represents the imported method "move-vertically".
//
// Moves `lines` display lines down, or up if negative, from `pos`.
// Aims for display `column`, or the column of `pos` when none.
// Returns the new position and the column aimed for; pass that
// column back to keep it across short lines.
//
//	move-vertically: func(pos: offset, lines: s32, column: option<u32>) -> result<tuple<offset,
//	u32>, error>
//
//go:nosplit
func (self View) MoveVertically(pos Offset, lines int32, column cm.Option[uint32]) (result cm.Result[TupleOffsetU32Shape, cm.Tuple[Offset, uint32], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0 := (uint64)(pos)
	lines0 := (uint32)(lines)
	column0, column1 := lower_OptionU32(column)
	wasmimport_ViewMoveVertically((uint32)(self0), (uint64)(pos0), (uint32)(lines0), (uint32)(column0), (uint32)(column1), &result)
	return
}

// Redo represents the imported method "redo".
//
//	redo: func() -> option<range>
//
//go:nosplit
func (self View) Redo() (result cm.Option[Range]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewRedo((uint32)(self0), &result)
	return
}

// Scroll represents the imported method "scroll".
//
// Scrolls without moving the cursor, and returns how many lines
// `amount` stands for, negative upward. Move the cursor as many
// lines to scroll with it, as Ctrl-d does; the core keeps the
// cursor in view either way.
//
//	scroll: func(amount: scroll-amount) -> s32
//
//go:nosplit
func (self View) Scroll(amount ScrollAmount) (result int32) {
	self0 := cm.Reinterpret[uint32](self)
	amount0, amount1 := lower_ScrollAmount(amount)
	result0 := wasmimport_ViewScroll((uint32)(self0), (uint32)(amount0), (uint32)(amount1))
	result = (int32)((uint32)(result0))
	return
}

// Selection represents the imported method "selection".
//
//	selection: func() -> selection
//
//go:nosplit
func (self View) Selection() (result Selection) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewSelection((uint32)(self0), &result)
	return
}

// SetCursorShape represents the imported method "set-cursor-shape".
//
//	set-cursor-shape: func(shape: cursor-shape)
//
//go:nosplit
func (self View) SetCursorShape(shape CursorShape) {
	self0 := cm.Reinterpret[uint32](self)
	shape0 := (uint32)(shape)
	wasmimport_ViewSetCursorShape((uint32)(self0), (uint32)(shape0))
	return
}

// SetSelection represents the imported method "set-selection".
//
//	set-selection: func(sel: selection) -> result<_, error>
//
//go:nosplit
func (self View) SetSelection(sel Selection) (result cm.Result[Error, struct{}, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	sel0, sel1, sel2 := lower_Selection(sel)
	wasmimport_ViewSetSelection((uint32)(self0), (*types.SelRange)(sel0), (uint32)(sel1), (uint32)(sel2), &result)
	return
}

// Show represents the imported method "show".
//
// Shows `buf` in it.
//
//	show: func(buf: borrow<buffer>)
//
//go:nosplit
func (self View) Show(buf Buffer) {
	self0 := cm.Reinterpret[uint32](self)
	buf0 := cm.Reinterpret[uint32](buf)
	wasmimport_ViewShow((uint32)(self0), (uint32)(buf0))
	return
}

// ShowNext represents the imported method "show-next".
//
// Shows the next or the previous open buffer.
//
//	show-next: func()
//
//go:nosplit
func (self View) ShowNext() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewShowNext((uint32)(self0))
	return
}

// ShowPrevious represents the imported method "show-previous".
//
//	show-previous: func()
//
//go:nosplit
func (self View) ShowPrevious() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewShowPrevious((uint32)(self0))
	return
}

// Undo represents the imported method "undo".
//
// Undoes a step and returns where the text changed: the first
// change, in the text after it. `none` when there is nothing to
// undo.
//
//	undo: func() -> option<range>
//
//go:nosplit
func (self View) Undo() (result cm.Option[Range]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewUndo((uint32)(self0), &result)
	return
}

// VisibleRange represents the imported method "visible-range".
//
// The part of the buffer on screen: from the start of the first line
// shown to the end of the last one.
//
//	visible-range: func() -> range
//
//go:nosplit
func (self View) VisibleRange() (result Range) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewVisibleRange((uint32)(self0), &result)
	return
}

// Active represents the imported function "active".
//
//	active: func() -> view
//
//go:nosplit
func Active() (result View) {
	result0 := wasmimport_Active()
	result = cm.Reinterpret[View]((uint32)(result0))
	return
}

// Split represents the imported function "split".
//
// Splits the focused view, side by side or one above the other; the
// new view shows the same buffer and takes the focus.
//
//	split: func(direction: direction)
//
//go:nosplit
func Split(direction Direction) {
	direction0 := (uint32)(direction)
	wasmimport_Split((uint32)(direction0))
	return
}

// Close represents the imported function "close".
//
// Closes the focused view; fails for the last one.
//
//	close: func() -> result<_, string>
//
//go:nosplit
func Close() (result cm.Result[string, struct{}, string]) {
	wasmimport_Close(&result)
	return
}

// Only represents the imported function "only".
//
// Closes every view but the focused one.
//
//	only: func()
//
//go:nosplit
func Only() {
	wasmimport_Only()
	return
}

// Focus represents the imported function "focus".
//
//	focus: func(toward: toward)
//
//go:nosplit
func Focus(toward Toward) {
	toward0 := (uint32)(toward)
	wasmimport_Focus((uint32)(toward0))
	return
}
