// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package editor represents the imported interface "nib:plugin/editor@0.7.1".
//
// The editor as a whole.
package editor

import (
	"go.bytecodealliance.org/cm"
)

// WorkingDirectory represents the imported function "working-directory".
//
// The editor's working directory, as an absolute path. Buffer paths
// are as they were opened, so they may be relative to it.
//
//	working-directory: func() -> string
//
//go:nosplit
func WorkingDirectory() (result string) {
	wasmimport_WorkingDirectory(&result)
	return
}

// Quit represents the imported function "quit".
//
// Quits; without `force`, fails when buffers have unsaved changes.
//
//	quit: func(force: bool) -> result<_, string>
//
//go:nosplit
func Quit(force bool) (result cm.Result[string, struct{}, string]) {
	force0 := (uint32)(cm.BoolToU32(force))
	wasmimport_Quit((uint32)(force0), &result)
	return
}

// OpenConfig represents the imported function "open-config".
//
// Opens config.toml, or with `plugin`, `plugins/<plugin>.toml`.
//
//	open-config: func(plugin: option<string>) -> result<_, string>
//
//go:nosplit
func OpenConfig(plugin cm.Option[string]) (result cm.Result[string, struct{}, string]) {
	plugin0, plugin1, plugin2 := lower_OptionString(plugin)
	wasmimport_OpenConfig((uint32)(plugin0), (*uint8)(plugin1), (uint32)(plugin2), &result)
	return
}

// ReloadConfig represents the imported function "reload-config".
//
// Reads the settings again.
//
//	reload-config: func()
//
//go:nosplit
func ReloadConfig() {
	wasmimport_ReloadConfig()
	return
}

// OpenMenu represents the imported function "open-menu".
//
// Opens the core menu.
//
//	open-menu: func()
//
//go:nosplit
func OpenMenu() {
	wasmimport_OpenMenu()
	return
}
