// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package editor represents the imported interface "nib:plugin/editor@0.5.0".
package editor

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Offset represents the type alias "nib:plugin/editor@0.5.0#offset".
//
// See [types.Offset] for more information.
type Offset = types.Offset

// Selection represents the type alias "nib:plugin/editor@0.5.0#selection".
//
// See [types.Selection] for more information.
type Selection = types.Selection

// Edit represents the type alias "nib:plugin/editor@0.5.0#edit".
//
// See [types.Edit] for more information.
type Edit = types.Edit

// UndoMode represents the type alias "nib:plugin/editor@0.5.0#undo-mode".
//
// See [types.UndoMode] for more information.
type UndoMode = types.UndoMode

// CursorShape represents the type alias "nib:plugin/editor@0.5.0#cursor-shape".
//
// See [types.CursorShape] for more information.
type CursorShape = types.CursorShape

// Error represents the variant "nib:plugin/editor@0.5.0#error".
//
//	variant error {
//		stale-version,
//		invalid-position,
//		overlapping-edits,
//		invalid-selection,
//		invalid-pattern(string),
//	}
type Error cm.Variant[uint8, string, string]

// ErrorStaleVersion returns a [Error] of case "stale-version".
//
// The change was built against an older version of the buffer.
func ErrorStaleVersion() Error {
	var data struct{}
	return cm.New[Error](0, data)
}

// StaleVersion returns true if [Error] represents the variant case "stale-version".
func (self *Error) StaleVersion() bool {
	return self.Tag() == 0
}

// ErrorInvalidPosition returns a [Error] of case "invalid-position".
//
// The offset is out of bounds or not on a char boundary.
func ErrorInvalidPosition() Error {
	var data struct{}
	return cm.New[Error](1, data)
}

// InvalidPosition returns true if [Error] represents the variant case "invalid-position".
func (self *Error) InvalidPosition() bool {
	return self.Tag() == 1
}

// ErrorOverlappingEdits returns a [Error] of case "overlapping-edits".
//
// Edits in one change overlap each other.
func ErrorOverlappingEdits() Error {
	var data struct{}
	return cm.New[Error](2, data)
}

// OverlappingEdits returns true if [Error] represents the variant case "overlapping-edits".
func (self *Error) OverlappingEdits() bool {
	return self.Tag() == 2
}

// ErrorInvalidSelection returns a [Error] of case "invalid-selection".
//
// A selection needs at least one range and a primary index in bounds.
func ErrorInvalidSelection() Error {
	var data struct{}
	return cm.New[Error](3, data)
}

// InvalidSelection returns true if [Error] represents the variant case "invalid-selection".
func (self *Error) InvalidSelection() bool {
	return self.Tag() == 3
}

// ErrorInvalidPattern returns a [Error] of case "invalid-pattern".
func ErrorInvalidPattern(data string) Error {
	return cm.New[Error](4, data)
}

// InvalidPattern returns a non-nil *[string] if [Error] represents the variant case "invalid-pattern".
func (self *Error) InvalidPattern() *string {
	return cm.Case[string](self, 4)
}

var _ErrorStrings = [5]string{
	"stale-version",
	"invalid-position",
	"overlapping-edits",
	"invalid-selection",
	"invalid-pattern",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Error) String() string {
	return _ErrorStrings[v.Tag()]
}

// Buffer represents the imported resource "nib:plugin/editor@0.5.0#buffer".
//
//	resource buffer
type Buffer cm.Resource

// ResourceDrop represents the imported resource-drop for resource "buffer".
//
// Drops a resource handle.
//
//go:nosplit
func (self Buffer) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BufferResourceDrop((uint32)(self0))
	return
}

// Find represents the imported method "find".
//
// The first match starting at or after `start`, or with `backward`,
// the last match ending at or before `start`. `^` and `$` match at
// every line.
//
//	find: func(pattern: string, start: offset, backward: bool) -> result<option<tuple<offset,
//	offset>>, error>
//
//go:nosplit
func (self Buffer) Find(pattern string, start Offset, backward bool) (result cm.Result[OptionTupleOffsetOffsetShape, cm.Option[[2]Offset], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pattern0, pattern1 := cm.LowerString(pattern)
	start0 := (uint64)(start)
	backward0 := (uint32)(cm.BoolToU32(backward))
	wasmimport_BufferFind((uint32)(self0), (*uint8)(pattern0), (uint32)(pattern1), (uint64)(start0), (uint32)(backward0), &result)
	return
}

// FindAll represents the imported method "find-all".
//
//	find-all: func(pattern: string, start: offset, end: offset) -> result<list<tuple<offset,
//	offset>>, error>
//
//go:nosplit
func (self Buffer) FindAll(pattern string, start Offset, end Offset) (result cm.Result[ErrorShape, cm.List[[2]Offset], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pattern0, pattern1 := cm.LowerString(pattern)
	start0 := (uint64)(start)
	end0 := (uint64)(end)
	wasmimport_BufferFindAll((uint32)(self0), (*uint8)(pattern0), (uint32)(pattern1), (uint64)(start0), (uint64)(end0), &result)
	return
}

// Len represents the imported method "len".
//
//	len: func() -> offset
//
//go:nosplit
func (self Buffer) Len() (result Offset) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_BufferLen((uint32)(self0))
	result = (types.Offset)((uint64)(result0))
	return
}

// LineCount represents the imported method "line-count".
//
// Text ending with a line break has an empty last line.
//
//	line-count: func() -> u64
//
//go:nosplit
func (self Buffer) LineCount() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_BufferLineCount((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// LineOf represents the imported method "line-of".
//
//	line-of: func(pos: offset) -> result<u64, error>
//
//go:nosplit
func (self Buffer) LineOf(pos Offset) (result cm.Result[ErrorShape, uint64, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0 := (uint64)(pos)
	wasmimport_BufferLineOf((uint32)(self0), (uint64)(pos0), &result)
	return
}

// LineStart represents the imported method "line-start".
//
//	line-start: func(line: u64) -> option<offset>
//
//go:nosplit
func (self Buffer) LineStart(line uint64) (result cm.Option[Offset]) {
	self0 := cm.Reinterpret[uint32](self)
	line0 := (uint64)(line)
	wasmimport_BufferLineStart((uint32)(self0), (uint64)(line0), &result)
	return
}

// NextGrapheme represents the imported method "next-grapheme".
//
//	next-grapheme: func(pos: offset) -> result<offset, error>
//
//go:nosplit
func (self Buffer) NextGrapheme(pos Offset) (result cm.Result[ErrorShape, Offset, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0 := (uint64)(pos)
	wasmimport_BufferNextGrapheme((uint32)(self0), (uint64)(pos0), &result)
	return
}

// Path represents the imported method "path".
//
//	path: func() -> option<string>
//
//go:nosplit
func (self Buffer) Path() (result cm.Option[string]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BufferPath((uint32)(self0), &result)
	return
}

// PrevGrapheme represents the imported method "prev-grapheme".
//
//	prev-grapheme: func(pos: offset) -> result<offset, error>
//
//go:nosplit
func (self Buffer) PrevGrapheme(pos Offset) (result cm.Result[ErrorShape, Offset, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0 := (uint64)(pos)
	wasmimport_BufferPrevGrapheme((uint32)(self0), (uint64)(pos0), &result)
	return
}

// Slice represents the imported method "slice".
//
//	slice: func(start: offset, end: offset) -> result<string, error>
//
//go:nosplit
func (self Buffer) Slice(start Offset, end Offset) (result cm.Result[ErrorShape, string, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	start0 := (uint64)(start)
	end0 := (uint64)(end)
	wasmimport_BufferSlice((uint32)(self0), (uint64)(start0), (uint64)(end0), &result)
	return
}

// Version represents the imported method "version".
//
// Increases on every change, including undo and redo.
//
//	version: func() -> u64
//
//go:nosplit
func (self Buffer) Version() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_BufferVersion((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// ScrollAmount represents the variant "nib:plugin/editor@0.5.0#scroll-amount".
//
//	variant scroll-amount {
//		lines(s32),
//		half-page(s32),
//		page(s32),
//	}
type ScrollAmount cm.Variant[uint8, int32, int32]

// ScrollAmountLines returns a [ScrollAmount] of case "lines".
func ScrollAmountLines(data int32) ScrollAmount {
	return cm.New[ScrollAmount](0, data)
}

// Lines returns a non-nil *[int32] if [ScrollAmount] represents the variant case "lines".
func (self *ScrollAmount) Lines() *int32 {
	return cm.Case[int32](self, 0)
}

// ScrollAmountHalfPage returns a [ScrollAmount] of case "half-page".
func ScrollAmountHalfPage(data int32) ScrollAmount {
	return cm.New[ScrollAmount](1, data)
}

// HalfPage returns a non-nil *[int32] if [ScrollAmount] represents the variant case "half-page".
func (self *ScrollAmount) HalfPage() *int32 {
	return cm.Case[int32](self, 1)
}

// ScrollAmountPage returns a [ScrollAmount] of case "page".
func ScrollAmountPage(data int32) ScrollAmount {
	return cm.New[ScrollAmount](2, data)
}

// Page returns a non-nil *[int32] if [ScrollAmount] represents the variant case "page".
func (self *ScrollAmount) Page() *int32 {
	return cm.Case[int32](self, 2)
}

var _ScrollAmountStrings = [3]string{
	"lines",
	"half-page",
	"page",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v ScrollAmount) String() string {
	return _ScrollAmountStrings[v.Tag()]
}

// View represents the imported resource "nib:plugin/editor@0.5.0#view".
//
//	resource view
type View cm.Resource

// ResourceDrop represents the imported resource-drop for resource "view".
//
// Drops a resource handle.
//
//go:nosplit
func (self View) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewResourceDrop((uint32)(self0))
	return
}

// Apply represents the imported method "apply".
//
// Applies `edits` atomically. Without `after`, the selection is
// mapped through the change.
//
//	apply: func(base-version: u64, edits: list<edit>, after: option<selection>, undo:
//	undo-mode) -> result<_, error>
//
//go:nosplit
func (self View) Apply(baseVersion uint64, edits cm.List[Edit], after cm.Option[Selection], undo UndoMode) (result cm.Result[Error, struct{}, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	baseVersion0 := (uint64)(baseVersion)
	edits0, edits1 := cm.LowerList(edits)
	after0, after1, after2, after3 := lower_OptionSelection(after)
	undo0 := (uint32)(undo)
	wasmimport_ViewApply((uint32)(self0), (uint64)(baseVersion0), (*Edit)(edits0), (uint32)(edits1), (uint32)(after0), (*types.SelRange)(after1), (uint32)(after2), (uint32)(after3), (uint32)(undo0), &result)
	return
}

// Buffer represents the imported method "buffer".
//
//	buffer: func() -> buffer
//
//go:nosplit
func (self View) Buffer() (result Buffer) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ViewBuffer((uint32)(self0))
	result = cm.Reinterpret[Buffer]((uint32)(result0))
	return
}

// MoveVertically represents the imported method "move-vertically".
//
// Moves `lines` display lines down, or up if negative, from `pos`.
// Aims for display `column`, or the column of `pos` when none.
// Returns the new position and the column aimed for; pass that
// column back to keep it across short lines.
//
//	move-vertically: func(pos: offset, lines: s32, column: option<u32>) -> result<tuple<offset,
//	u32>, error>
//
//go:nosplit
func (self View) MoveVertically(pos Offset, lines int32, column cm.Option[uint32]) (result cm.Result[TupleOffsetU32Shape, cm.Tuple[Offset, uint32], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0 := (uint64)(pos)
	lines0 := (uint32)(lines)
	column0, column1 := lower_OptionU32(column)
	wasmimport_ViewMoveVertically((uint32)(self0), (uint64)(pos0), (uint32)(lines0), (uint32)(column0), (uint32)(column1), &result)
	return
}

// Redo represents the imported method "redo".
//
//	redo: func() -> bool
//
//go:nosplit
func (self View) Redo() (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ViewRedo((uint32)(self0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Scroll represents the imported method "scroll".
//
// Scrolls without moving the cursor, and returns how many lines
// `amount` stands for, negative upward. Move the cursor as many
// lines to scroll with it, as Ctrl-d does; the core keeps the
// cursor in view either way.
//
//	scroll: func(amount: scroll-amount) -> s32
//
//go:nosplit
func (self View) Scroll(amount ScrollAmount) (result int32) {
	self0 := cm.Reinterpret[uint32](self)
	amount0, amount1 := lower_ScrollAmount(amount)
	result0 := wasmimport_ViewScroll((uint32)(self0), (uint32)(amount0), (uint32)(amount1))
	result = (int32)((uint32)(result0))
	return
}

// Selection represents the imported method "selection".
//
//	selection: func() -> selection
//
//go:nosplit
func (self View) Selection() (result Selection) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewSelection((uint32)(self0), &result)
	return
}

// SetCursorShape represents the imported method "set-cursor-shape".
//
//	set-cursor-shape: func(shape: cursor-shape)
//
//go:nosplit
func (self View) SetCursorShape(shape CursorShape) {
	self0 := cm.Reinterpret[uint32](self)
	shape0 := (uint32)(shape)
	wasmimport_ViewSetCursorShape((uint32)(self0), (uint32)(shape0))
	return
}

// SetSelection represents the imported method "set-selection".
//
//	set-selection: func(sel: selection) -> result<_, error>
//
//go:nosplit
func (self View) SetSelection(sel Selection) (result cm.Result[Error, struct{}, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	sel0, sel1, sel2 := lower_Selection(sel)
	wasmimport_ViewSetSelection((uint32)(self0), (*types.SelRange)(sel0), (uint32)(sel1), (uint32)(sel2), &result)
	return
}

// Undo represents the imported method "undo".
//
// Returns false when there is nothing to undo.
//
//	undo: func() -> bool
//
//go:nosplit
func (self View) Undo() (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ViewUndo((uint32)(self0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// VisibleRange represents the imported method "visible-range".
//
// The part of the buffer on screen: from the start of the first line
// shown to the end of the last one.
//
//	visible-range: func() -> tuple<offset, offset>
//
//go:nosplit
func (self View) VisibleRange() (result [2]Offset) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ViewVisibleRange((uint32)(self0), &result)
	return
}

// ActiveView represents the imported function "active-view".
//
//	active-view: func() -> view
//
//go:nosplit
func ActiveView() (result View) {
	result0 := wasmimport_ActiveView()
	result = cm.Reinterpret[View]((uint32)(result0))
	return
}

// Buffers represents the imported function "buffers".
//
// Every open buffer, e.g. for a plugin enabled after files were opened.
//
//	buffers: func() -> list<buffer>
//
//go:nosplit
func Buffers() (result cm.List[Buffer]) {
	wasmimport_Buffers(&result)
	return
}

// WorkingDirectory represents the imported function "working-directory".
//
// The editor's working directory, as an absolute path. Buffer paths
// are as they were opened, so they may be relative to it.
//
//	working-directory: func() -> string
//
//go:nosplit
func WorkingDirectory() (result string) {
	wasmimport_WorkingDirectory(&result)
	return
}
