// Code generated by wit-bindgen-go. DO NOT EDIT.

package timers

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.7.0".

//go:wasmimport nib:plugin/timers@0.7.0 set
//go:noescape
func wasmimport_Set(ms0 uint32) (result0 uint64)

//go:wasmimport nib:plugin/timers@0.7.0 cancel
//go:noescape
func wasmimport_Cancel(id0 uint64)
