// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package timers represents the imported interface "nib:plugin/timers@0.7.0".
package timers

// Set represents the imported function "set".
//
// Sends `timer(id)` once, `ms` milliseconds from now, and returns `id`.
// Timers are checked between keys, never during a call.
//
//	set: func(ms: u32) -> u64
//
//go:nosplit
func Set(ms uint32) (result uint64) {
	ms0 := (uint32)(ms)
	result0 := wasmimport_Set((uint32)(ms0))
	result = (uint64)((uint64)(result0))
	return
}

// Cancel represents the imported function "cancel".
//
//	cancel: func(id: u64)
//
//go:nosplit
func Cancel(id uint64) {
	id0 := (uint64)(id)
	wasmimport_Cancel((uint64)(id0))
	return
}
