// Code generated by wit-bindgen-go. DO NOT EDIT.

package prompt

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

func lower_OptionU64(v cm.Option[uint64]) (f0 uint32, f1 uint64) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1 := (uint64)(*some)
		f1 = (uint64)(v1)
	}
	return
}

func lower_FilePreview(v FilePreview) (f0 *uint8, f1 uint32, f2 uint32, f3 uint64) {
	f0, f1 = cm.LowerString(v.Path)
	f2, f3 = lower_OptionU64(v.Line)
	return
}

func lower_Preview(v Preview) (f0 uint32, f1 uint32, f2 uint32, f3 uint32, f4 uint64) {
	f0 = (uint32)(v.Tag())
	switch f0 {
	case 1: // lines
		v1, v2 := cm.LowerList(*cm.Case[cm.List[StyledLine]](&v, 1))
		f1 = (uint32)(cm.PointerToU32(v1))
		f2 = (uint32)(v2)
	case 2: // file
		v1, v2, v3, v4 := lower_FilePreview(*cm.Case[FilePreview](&v, 2))
		f1 = (uint32)(cm.PointerToU32(v1))
		f2 = (uint32)(v2)
		f3 = (uint32)(v3)
		f4 = (uint64)(v4)
	}
	return
}

func lower_OptionU32(v cm.Option[uint32]) (f0 uint32, f1 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1 := (uint32)(*some)
		f1 = (uint32)(v1)
	}
	return
}

// FilePreviewShape is used for storage in variant or result types.
type FilePreviewShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(FilePreview{})]byte
}
