// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package prompt represents the imported interface "nib:plugin/prompt@0.5.2".
//
// A line of text being typed, such as a command line or a picker's query.
// The plugin that opens one owns it and hears what happens to it through
// events; the base in use decides what each key does to it.
package prompt

import (
	"go.bytecodealliance.org/cm"
)

// Action represents the enum "nib:plugin/prompt@0.5.2#action".
//
// What a key can ask of a prompt's owner, besides editing the text.
//
//	enum action {
//		accept,
//		cancel,
//		next,
//		previous,
//		complete,
//		complete-back
//	}
type Action uint8

const (
	// Take the text, as Enter does.
	ActionAccept Action = iota

	// Give up, as Escape does.
	ActionCancel

	// The next candidate, as Down does.
	ActionNext
	ActionPrevious

	// Complete what is typed, as Tab does.
	ActionComplete

	// Back to the completion before, as Shift-Tab does.
	ActionCompleteBack
)

var _ActionStrings = [6]string{
	"accept",
	"cancel",
	"next",
	"previous",
	"complete",
	"complete-back",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Action) String() string {
	return _ActionStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Action) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Action) UnmarshalText(text []byte) error {
	return _ActionUnmarshalCase(e, text)
}

var _ActionUnmarshalCase = cm.CaseUnmarshaler[Action](_ActionStrings[:])

// Line represents the imported resource "nib:plugin/prompt@0.5.2#line".
//
// Drawn above the status line, with `label` in front. While it is the
// newest one open, keys go to the base in use instead of the input
// stack. Dropping it closes it.
//
//	resource line
type Line cm.Resource

// ResourceDrop represents the imported resource-drop for resource "line".
//
// Drops a resource handle.
//
//go:nosplit
func (self Line) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_LineResourceDrop((uint32)(self0))
	return
}

// NewLine represents the imported constructor for resource "line".
//
//	constructor(label: string)
//
//go:nosplit
func NewLine(label string) (result Line) {
	label0, label1 := cm.LowerString(label)
	result0 := wasmimport_NewLine((*uint8)(label0), (uint32)(label1))
	result = cm.Reinterpret[Line]((uint32)(result0))
	return
}

// Cursor represents the imported method "cursor".
//
// A byte offset into the text.
//
//	cursor: func() -> u32
//
//go:nosplit
func (self Line) Cursor() (result uint32) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_LineCursor((uint32)(self0))
	result = (uint32)((uint32)(result0))
	return
}

// ID represents the imported method "id".
//
// The id its events carry.
//
//	id: func() -> u64
//
//go:nosplit
func (self Line) ID() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_LineID((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// Set represents the imported method "set".
//
// Replaces the text, as when completing; no event follows. The
// cursor is moved back to a char boundary and into the text.
//
//	set: func(text: string, cursor: u32)
//
//go:nosplit
func (self Line) Set(text string, cursor uint32) {
	self0 := cm.Reinterpret[uint32](self)
	text0, text1 := cm.LowerString(text)
	cursor0 := (uint32)(cursor)
	wasmimport_LineSet((uint32)(self0), (*uint8)(text0), (uint32)(text1), (uint32)(cursor0))
	return
}

// SetHint represents the imported method "set-hint".
//
// Shown at the right end, such as "3/10".
//
//	set-hint: func(hint: string)
//
//go:nosplit
func (self Line) SetHint(hint string) {
	self0 := cm.Reinterpret[uint32](self)
	hint0, hint1 := cm.LowerString(hint)
	wasmimport_LineSetHint((uint32)(self0), (*uint8)(hint0), (uint32)(hint1))
	return
}

// Text represents the imported method "text".
//
//	text: func() -> string
//
//go:nosplit
func (self Line) Text() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_LineText((uint32)(self0), &result)
	return
}

// Choices represents the imported resource "nib:plugin/prompt@0.5.2#choices".
//
// A list shown without a line to type into, such as completions, which
// its owner draws. While it is the newest one open and no prompt is,
// the base turns its own keys for `actions` into `prompt-action`
// events for it. A key that does not act on it is handled as usual,
// and sends `cancel` before the events it causes, as the list no
// longer fits. Dropping it closes it.
//
//	resource choices
type Choices cm.Resource

// ResourceDrop represents the imported resource-drop for resource "choices".
//
// Drops a resource handle.
//
//go:nosplit
func (self Choices) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ChoicesResourceDrop((uint32)(self0))
	return
}

// NewChoices represents the imported constructor for resource "choices".
//
//	constructor(actions: list<action>)
//
//go:nosplit
func NewChoices(actions cm.List[Action]) (result Choices) {
	actions0, actions1 := cm.LowerList(actions)
	result0 := wasmimport_NewChoices((*Action)(actions0), (uint32)(actions1))
	result = cm.Reinterpret[Choices]((uint32)(result0))
	return
}

// ID represents the imported method "id".
//
// The id its events carry.
//
//	id: func() -> u64
//
//go:nosplit
func (self Choices) ID() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ChoicesID((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// State represents the record "nib:plugin/prompt@0.5.2#state".
//
// The prompt keys go to; `mine` if the caller opened it.
//
//	record state {
//		id: u64,
//		label: string,
//		text: string,
//		cursor: u32,
//		mine: bool,
//	}
type State struct {
	_      cm.HostLayout `json:"-"`
	ID     uint64        `json:"id"`
	Label  string        `json:"label"`
	Text   string        `json:"text"`
	Cursor uint32        `json:"cursor"`
	Mine   bool          `json:"mine"`
}

// Offer represents the record "nib:plugin/prompt@0.5.2#offer".
//
// Choices keys may act on: their id, and the actions they take.
//
//	record offer {
//		id: u64,
//		actions: list<action>,
//	}
type Offer struct {
	_       cm.HostLayout   `json:"-"`
	ID      uint64          `json:"id"`
	Actions cm.List[Action] `json:"actions"`
}

// Active represents the imported function "active".
//
// For the base: the prompt keys go to, if one is open.
//
//	active: func() -> option<state>
//
//go:nosplit
func Active() (result cm.Option[State]) {
	wasmimport_Active(&result)
	return
}

// Edit represents the imported function "edit".
//
// For the base: replaces the active prompt's text; its owner gets
// `prompt-changed`.
//
//	edit: func(text: string, cursor: u32)
//
//go:nosplit
func Edit(text string, cursor uint32) {
	text0, text1 := cm.LowerString(text)
	cursor0 := (uint32)(cursor)
	wasmimport_Edit((*uint8)(text0), (uint32)(text1), (uint32)(cursor0))
	return
}

// Offered represents the imported function "offered".
//
// For the base: the newest choices, while no prompt is open.
//
//	offered: func() -> option<offer>
//
//go:nosplit
func Offered() (result cm.Option[Offer]) {
	wasmimport_Offered(&result)
	return
}

// Act represents the imported function "act".
//
// For the base: sends `action` as `prompt-action` to the owner of the
// active prompt, or else of the offered choices.
//
//	act: func(action: action)
//
//go:nosplit
func Act(action Action) {
	action0 := (uint32)(action)
	wasmimport_Act((uint32)(action0))
	return
}
