// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package prompt represents the imported interface "nib:plugin/prompt@0.7.3".
//
// A line of text being typed, such as a command line or a picker's query.
// The plugin that opens one owns it and hears what happens to it through
// events; the base in use decides what each key does to it.
package prompt

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/types"
	"go.bytecodealliance.org/cm"
)

// StyledLine represents the type alias "nib:plugin/prompt@0.7.3#styled-line".
//
// See [types.StyledLine] for more information.
type StyledLine = types.StyledLine

// Action represents the enum "nib:plugin/prompt@0.7.3#action".
//
// What a key can ask of a prompt's owner, besides editing the text.
//
//	enum action {
//		accept,
//		cancel,
//		next,
//		previous,
//		page-next,
//		page-previous,
//		complete,
//		complete-back
//	}
type Action uint8

const (
	// Take the text, as Enter does.
	ActionAccept Action = iota

	// Give up, as Escape does.
	ActionCancel

	// The next candidate, as Down does.
	ActionNext
	ActionPrevious

	// A screen of candidates further, as PageDown does.
	ActionPageNext
	ActionPagePrevious

	// Complete what is typed, as Tab does.
	ActionComplete

	// Back to the completion before, as Shift-Tab does.
	ActionCompleteBack
)

var _ActionStrings = [8]string{
	"accept",
	"cancel",
	"next",
	"previous",
	"page-next",
	"page-previous",
	"complete",
	"complete-back",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Action) String() string {
	return _ActionStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Action) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Action) UnmarshalText(text []byte) error {
	return _ActionUnmarshalCase(e, text)
}

var _ActionUnmarshalCase = cm.CaseUnmarshaler[Action](_ActionStrings[:])

// Line represents the imported resource "nib:plugin/prompt@0.7.3#line".
//
// Drawn above the status line, with `label` in front. While it is the
// newest one open, keys go to the base in use instead of the input
// stack. Dropping it closes it.
//
//	resource line
type Line cm.Resource

// ResourceDrop represents the imported resource-drop for resource "line".
//
// Drops a resource handle.
//
//go:nosplit
func (self Line) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_LineResourceDrop((uint32)(self0))
	return
}

// NewLine represents the imported constructor for resource "line".
//
//	constructor(label: string)
//
//go:nosplit
func NewLine(label string) (result Line) {
	label0, label1 := cm.LowerString(label)
	result0 := wasmimport_NewLine((*uint8)(label0), (uint32)(label1))
	result = cm.Reinterpret[Line]((uint32)(result0))
	return
}

// Cursor represents the imported method "cursor".
//
// A byte offset into the text.
//
//	cursor: func() -> u32
//
//go:nosplit
func (self Line) Cursor() (result uint32) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_LineCursor((uint32)(self0))
	result = (uint32)((uint32)(result0))
	return
}

// ID represents the imported method "id".
//
// The id its events carry.
//
//	id: func() -> u64
//
//go:nosplit
func (self Line) ID() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_LineID((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// Set represents the imported method "set".
//
// Replaces the text, as when completing; no event follows. The
// cursor is moved back to a char boundary and into the text.
//
//	set: func(text: string, cursor: u32)
//
//go:nosplit
func (self Line) Set(text string, cursor uint32) {
	self0 := cm.Reinterpret[uint32](self)
	text0, text1 := cm.LowerString(text)
	cursor0 := (uint32)(cursor)
	wasmimport_LineSet((uint32)(self0), (*uint8)(text0), (uint32)(text1), (uint32)(cursor0))
	return
}

// SetHint represents the imported method "set-hint".
//
// Shown at the right end, such as "3/10".
//
//	set-hint: func(hint: string)
//
//go:nosplit
func (self Line) SetHint(hint string) {
	self0 := cm.Reinterpret[uint32](self)
	hint0, hint1 := cm.LowerString(hint)
	wasmimport_LineSetHint((uint32)(self0), (*uint8)(hint0), (uint32)(hint1))
	return
}

// SetLabel represents the imported method "set-label".
//
//	set-label: func(label: string)
//
//go:nosplit
func (self Line) SetLabel(label string) {
	self0 := cm.Reinterpret[uint32](self)
	label0, label1 := cm.LowerString(label)
	wasmimport_LineSetLabel((uint32)(self0), (*uint8)(label0), (uint32)(label1))
	return
}

// SetPreview represents the imported method "set-preview".
//
// What the box shows beside the rows.
//
//	set-preview: func(preview: preview)
//
//go:nosplit
func (self Line) SetPreview(preview Preview) {
	self0 := cm.Reinterpret[uint32](self)
	preview0, preview1, preview2, preview3, preview4 := lower_Preview(preview)
	wasmimport_LineSetPreview((uint32)(self0), (uint32)(preview0), (uint32)(preview1), (uint32)(preview2), (uint32)(preview3), (uint64)(preview4))
	return
}

// SetRows represents the imported method "set-rows".
//
// The rows under the input in the box, and the one selected. A
// window of rows around the selected one is enough: the box shows
// as many as fit, with the selected one among them.
//
//	set-rows: func(rows: list<styled-line>, selected: option<u32>)
//
//go:nosplit
func (self Line) SetRows(rows cm.List[StyledLine], selected cm.Option[uint32]) {
	self0 := cm.Reinterpret[uint32](self)
	rows0, rows1 := cm.LowerList(rows)
	selected0, selected1 := lower_OptionU32(selected)
	wasmimport_LineSetRows((uint32)(self0), (*StyledLine)(rows0), (uint32)(rows1), (uint32)(selected0), (uint32)(selected1))
	return
}

// ShowInBox represents the imported method "show-in-box".
//
// Shows it as the input of a box in the middle of the screen, as
// the core menu, titled `title`, with the rows of `set-rows` under
// it and `set-preview` beside them (docs/finder.md). Without it,
// it is drawn above the status line.
//
//	show-in-box: func(title: string)
//
//go:nosplit
func (self Line) ShowInBox(title string) {
	self0 := cm.Reinterpret[uint32](self)
	title0, title1 := cm.LowerString(title)
	wasmimport_LineShowInBox((uint32)(self0), (*uint8)(title0), (uint32)(title1))
	return
}

// Text represents the imported method "text".
//
//	text: func() -> string
//
//go:nosplit
func (self Line) Text() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_LineText((uint32)(self0), &result)
	return
}

// FilePreview represents the record "nib:plugin/prompt@0.7.3#file-preview".
//
//	record file-preview {
//		path: string,
//		line: option<u64>,
//	}
type FilePreview struct {
	_    cm.HostLayout     `json:"-"`
	Path string            `json:"path"`
	Line cm.Option[uint64] `json:"line"`
}

// Preview represents the variant "nib:plugin/prompt@0.7.3#preview".
//
//	variant preview {
//		none,
//		lines(list<styled-line>),
//		file(file-preview),
//	}
type Preview cm.Variant[uint8, FilePreviewShape, FilePreview]

// PreviewNone returns a [Preview] of case "none".
func PreviewNone() Preview {
	var data struct{}
	return cm.New[Preview](0, data)
}

// None returns true if [Preview] represents the variant case "none".
func (self *Preview) None() bool {
	return self.Tag() == 0
}

// PreviewLines returns a [Preview] of case "lines".
//
// Lines of text, such as a command's description.
func PreviewLines(data cm.List[StyledLine]) Preview {
	return cm.New[Preview](1, data)
}

// Lines returns a non-nil *[cm.List[StyledLine]] if [Preview] represents the variant case "lines".
func (self *Preview) Lines() *cm.List[StyledLine] {
	return cm.Case[cm.List[StyledLine]](self, 1)
}

// PreviewFile returns a [Preview] of case "file".
//
// The start of a file, colored as its language; or, with `line`,
// the lines around that one, which is marked. The core reads the
// file, and the plugin never sees it.
func PreviewFile(data FilePreview) Preview {
	return cm.New[Preview](2, data)
}

// File returns a non-nil *[FilePreview] if [Preview] represents the variant case "file".
func (self *Preview) File() *FilePreview {
	return cm.Case[FilePreview](self, 2)
}

var _PreviewStrings = [3]string{
	"none",
	"lines",
	"file",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Preview) String() string {
	return _PreviewStrings[v.Tag()]
}

// Choices represents the imported resource "nib:plugin/prompt@0.7.3#choices".
//
// A list shown without a line to type into, such as completions, which
// its owner draws. While it is the newest one open and no prompt is,
// the base turns its own keys for `actions` into `prompt-action`
// events for it. A key that does not act on it is handled as usual,
// and sends `cancel` before the events it causes, as the list no
// longer fits. Dropping it closes it.
//
//	resource choices
type Choices cm.Resource

// ResourceDrop represents the imported resource-drop for resource "choices".
//
// Drops a resource handle.
//
//go:nosplit
func (self Choices) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ChoicesResourceDrop((uint32)(self0))
	return
}

// NewChoices represents the imported constructor for resource "choices".
//
//	constructor(actions: list<action>)
//
//go:nosplit
func NewChoices(actions cm.List[Action]) (result Choices) {
	actions0, actions1 := cm.LowerList(actions)
	result0 := wasmimport_NewChoices((*Action)(actions0), (uint32)(actions1))
	result = cm.Reinterpret[Choices]((uint32)(result0))
	return
}

// ID represents the imported method "id".
//
// The id its events carry.
//
//	id: func() -> u64
//
//go:nosplit
func (self Choices) ID() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ChoicesID((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// State represents the record "nib:plugin/prompt@0.7.3#state".
//
// The prompt keys go to; `mine` if the caller opened it.
//
//	record state {
//		id: u64,
//		label: string,
//		text: string,
//		cursor: u32,
//		mine: bool,
//	}
type State struct {
	_      cm.HostLayout `json:"-"`
	ID     uint64        `json:"id"`
	Label  string        `json:"label"`
	Text   string        `json:"text"`
	Cursor uint32        `json:"cursor"`
	Mine   bool          `json:"mine"`
}

// Offer represents the record "nib:plugin/prompt@0.7.3#offer".
//
// Choices keys may act on: their id, and the actions they take.
//
//	record offer {
//		id: u64,
//		actions: list<action>,
//	}
type Offer struct {
	_       cm.HostLayout   `json:"-"`
	ID      uint64          `json:"id"`
	Actions cm.List[Action] `json:"actions"`
}

// Active represents the imported function "active".
//
// For the base: the prompt keys go to, if one is open.
//
//	active: func() -> option<state>
//
//go:nosplit
func Active() (result cm.Option[State]) {
	wasmimport_Active(&result)
	return
}

// Edit represents the imported function "edit".
//
// For the base: replaces the active prompt's text; its owner gets
// `prompt-changed`.
//
//	edit: func(text: string, cursor: u32)
//
//go:nosplit
func Edit(text string, cursor uint32) {
	text0, text1 := cm.LowerString(text)
	cursor0 := (uint32)(cursor)
	wasmimport_Edit((*uint8)(text0), (uint32)(text1), (uint32)(cursor0))
	return
}

// Offered represents the imported function "offered".
//
// For the base: the newest choices, while no prompt is open.
//
//	offered: func() -> option<offer>
//
//go:nosplit
func Offered() (result cm.Option[Offer]) {
	wasmimport_Offered(&result)
	return
}

// Act represents the imported function "act".
//
// For the base: sends `action` as `prompt-action` to the owner of the
// active prompt, or else of the offered choices.
//
//	act: func(action: action)
//
//go:nosplit
func Act(action Action) {
	action0 := (uint32)(action)
	wasmimport_Act((uint32)(action0))
	return
}
