// Code generated by wit-bindgen-go. DO NOT EDIT.

package settings

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.5.0".

//go:wasmimport nib:plugin/settings@0.5.0 get
//go:noescape
func wasmimport_Get(key0 *uint8, key1 uint32, result *cm.Option[string])

//go:wasmimport nib:plugin/settings@0.5.0 get-for
//go:noescape
func wasmimport_GetFor(buf0 uint32, key0 *uint8, key1 uint32, result *cm.Option[string])

//go:wasmimport nib:plugin/settings@0.5.0 set-for
//go:noescape
func wasmimport_SetFor(buf0 uint32, key0 *uint8, key1 uint32, value0 uint32, value1 *uint8, value2 uint32, result *cm.Result[string, struct{}, string])
