// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package settings represents the imported interface "nib:plugin/settings@0.6.0".
package settings

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/buffer"
	"go.bytecodealliance.org/cm"
)

// Buffer represents the imported type alias "nib:plugin/settings@0.6.0#buffer".
//
// See [buffer.Buffer] for more information.
type Buffer = buffer.Buffer

// Indentation represents the variant "nib:plugin/settings@0.6.0#indentation".
//
// How a level of indentation is made.
//
//	variant indentation {
//		spaces(u8),
//		tab,
//	}
type Indentation cm.Variant[uint8, uint8, uint8]

// IndentationSpaces returns a [Indentation] of case "spaces".
func IndentationSpaces(data uint8) Indentation {
	return cm.New[Indentation](0, data)
}

// Spaces returns a non-nil *[uint8] if [Indentation] represents the variant case "spaces".
func (self *Indentation) Spaces() *uint8 {
	return cm.Case[uint8](self, 0)
}

// IndentationTab returns a [Indentation] of case "tab".
func IndentationTab() Indentation {
	var data struct{}
	return cm.New[Indentation](1, data)
}

// Tab returns true if [Indentation] represents the variant case "tab".
func (self *Indentation) Tab() bool {
	return self.Tag() == 1
}

var _IndentationStrings = [2]string{
	"spaces",
	"tab",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Indentation) String() string {
	return _IndentationStrings[v.Tag()]
}

// TabWidth represents the imported function "tab-width".
//
// The editing settings of `buf`: config.toml's, or what a plugin set
// for it alone.
//
//	tab-width: func(buf: borrow<buffer>) -> u8
//
//go:nosplit
func TabWidth(buf Buffer) (result uint8) {
	buf0 := cm.Reinterpret[uint32](buf)
	result0 := wasmimport_TabWidth((uint32)(buf0))
	result = (uint8)((uint32)(result0))
	return
}

// Indent represents the imported function "indent".
//
//	indent: func(buf: borrow<buffer>) -> indentation
//
//go:nosplit
func Indent(buf Buffer) (result Indentation) {
	buf0 := cm.Reinterpret[uint32](buf)
	wasmimport_Indent((uint32)(buf0), &result)
	return
}

// ScrollMargin represents the imported function "scroll-margin".
//
// Lines kept between the cursor and the edge of the view.
//
//	scroll-margin: func() -> u32
//
//go:nosplit
func ScrollMargin() (result uint32) {
	result0 := wasmimport_ScrollMargin()
	result = (uint32)((uint32)(result0))
	return
}

// SetTabWidth represents the imported function "set-tab-width".
//
// Sets the tab width for `buf` alone (1 to 16), over config.toml's;
// `none` goes back to it. The last plugin to set a value wins, and what
// a plugin set goes away when it stops.
//
//	set-tab-width: func(buf: borrow<buffer>, width: option<u8>) -> result<_, string>
//
//go:nosplit
func SetTabWidth(buf Buffer, width cm.Option[uint8]) (result cm.Result[string, struct{}, string]) {
	buf0 := cm.Reinterpret[uint32](buf)
	width0, width1 := lower_OptionU8(width)
	wasmimport_SetTabWidth((uint32)(buf0), (uint32)(width0), (uint32)(width1), &result)
	return
}

// SetIndent represents the imported function "set-indent".
//
//	set-indent: func(buf: borrow<buffer>, indent: option<indentation>) -> result<_,
//	string>
//
//go:nosplit
func SetIndent(buf Buffer, indent cm.Option[Indentation]) (result cm.Result[string, struct{}, string]) {
	buf0 := cm.Reinterpret[uint32](buf)
	indent0, indent1, indent2 := lower_OptionIndentation(indent)
	wasmimport_SetIndent((uint32)(buf0), (uint32)(indent0), (uint32)(indent1), (uint32)(indent2), &result)
	return
}
