// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package settings represents the imported interface "nib:plugin/settings@0.5.1".
package settings

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/editor"
	"go.bytecodealliance.org/cm"
)

// Buffer represents the imported type alias "nib:plugin/settings@0.5.1#buffer".
//
// See [editor.Buffer] for more information.
type Buffer = editor.Buffer

// Get represents the imported function "get".
//
// An editing setting as JSON, for the shown buffer: "tab-width",
// "indent" (a number of spaces or "tab"), or "scroll-margin".
//
//	get: func(key: string) -> option<string>
//
//go:nosplit
func Get(key string) (result cm.Option[string]) {
	key0, key1 := cm.LowerString(key)
	wasmimport_Get((*uint8)(key0), (uint32)(key1), &result)
	return
}

// GetFor represents the imported function "get-for".
//
// An editing setting for `buf`.
//
//	get-for: func(buf: borrow<buffer>, key: string) -> option<string>
//
//go:nosplit
func GetFor(buf Buffer, key string) (result cm.Option[string]) {
	buf0 := cm.Reinterpret[uint32](buf)
	key0, key1 := cm.LowerString(key)
	wasmimport_GetFor((uint32)(buf0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// SetFor represents the imported function "set-for".
//
// Sets "tab-width" or "indent" for `buf` alone, over config.toml's
// value; `none` goes back to it. The last plugin to set a key wins, and
// what a plugin set goes away when it stops.
//
//	set-for: func(buf: borrow<buffer>, key: string, value: option<string>) -> result<_,
//	string>
//
//go:nosplit
func SetFor(buf Buffer, key string, value cm.Option[string]) (result cm.Result[string, struct{}, string]) {
	buf0 := cm.Reinterpret[uint32](buf)
	key0, key1 := cm.LowerString(key)
	value0, value1, value2 := lower_OptionString(value)
	wasmimport_SetFor((uint32)(buf0), (*uint8)(key0), (uint32)(key1), (uint32)(value0), (*uint8)(value1), (uint32)(value2), &result)
	return
}
