// Code generated by wit-bindgen-go. DO NOT EDIT.

package buffer

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// OptionRangeShape is used for storage in variant or result types.
type OptionRangeShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[Range]{})]byte
}

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}

// OptionListOptionRangeShape is used for storage in variant or result types.
type OptionListOptionRangeShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[cm.List[cm.Option[Range]]]{})]byte
}

func lower_OptionString(v cm.Option[string]) (f0 uint32, f1 *uint8, f2 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2 := cm.LowerString(*some)
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}
