// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package buffer represents the imported interface "nib:plugin/buffer@0.6.0".
package buffer

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Offset represents the type alias "nib:plugin/buffer@0.6.0#offset".
//
// See [types.Offset] for more information.
type Offset = types.Offset

// Range represents the type alias "nib:plugin/buffer@0.6.0#range".
//
// See [types.Range] for more information.
type Range = types.Range

// Error represents the type alias "nib:plugin/buffer@0.6.0#error".
//
// See [types.Error] for more information.
type Error = types.Error

// Buffer represents the imported resource "nib:plugin/buffer@0.6.0#buffer".
//
//	resource buffer
type Buffer cm.Resource

// ResourceDrop represents the imported resource-drop for resource "buffer".
//
// Drops a resource handle.
//
//go:nosplit
func (self Buffer) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BufferResourceDrop((uint32)(self0))
	return
}

// Close represents the imported method "close".
//
// Closes it; views that showed it show the buffer before. Without
// `force`, fails when it has unsaved changes. Its handles can no
// longer be used.
//
//	close: func(force: bool) -> result<_, string>
//
//go:nosplit
func (self Buffer) Close(force bool) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	force0 := (uint32)(cm.BoolToU32(force))
	wasmimport_BufferClose((uint32)(self0), (uint32)(force0), &result)
	return
}

// Find represents the imported method "find".
//
// The first match starting at or after `start`, or with `backward`,
// the last match ending at or before `start`. `^` and `$` match at
// every line.
//
//	find: func(pattern: string, start: offset, backward: bool) -> result<option<range>,
//	error>
//
//go:nosplit
func (self Buffer) Find(pattern string, start Offset, backward bool) (result cm.Result[OptionRangeShape, cm.Option[Range], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pattern0, pattern1 := cm.LowerString(pattern)
	start0 := (uint64)(start)
	backward0 := (uint32)(cm.BoolToU32(backward))
	wasmimport_BufferFind((uint32)(self0), (*uint8)(pattern0), (uint32)(pattern1), (uint64)(start0), (uint32)(backward0), &result)
	return
}

// FindAll represents the imported method "find-all".
//
//	find-all: func(pattern: string, start: offset, end: offset) -> result<list<range>,
//	error>
//
//go:nosplit
func (self Buffer) FindAll(pattern string, start Offset, end Offset) (result cm.Result[ErrorShape, cm.List[Range], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pattern0, pattern1 := cm.LowerString(pattern)
	start0 := (uint64)(start)
	end0 := (uint64)(end)
	wasmimport_BufferFindAll((uint32)(self0), (*uint8)(pattern0), (uint32)(pattern1), (uint64)(start0), (uint64)(end0), &result)
	return
}

// FindGroups represents the imported method "find-groups".
//
// As `find`, with the pattern's groups: the whole match first, then
// each group, `none` for a group that took no part.
//
//	find-groups: func(pattern: string, start: offset, backward: bool) -> result<option<list<option<range>>>,
//	error>
//
//go:nosplit
func (self Buffer) FindGroups(pattern string, start Offset, backward bool) (result cm.Result[OptionListOptionRangeShape, cm.Option[cm.List[cm.Option[Range]]], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pattern0, pattern1 := cm.LowerString(pattern)
	start0 := (uint64)(start)
	backward0 := (uint32)(cm.BoolToU32(backward))
	wasmimport_BufferFindGroups((uint32)(self0), (*uint8)(pattern0), (uint32)(pattern1), (uint64)(start0), (uint32)(backward0), &result)
	return
}

// Len represents the imported method "len".
//
//	len: func() -> offset
//
//go:nosplit
func (self Buffer) Len() (result Offset) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_BufferLen((uint32)(self0))
	result = (types.Offset)((uint64)(result0))
	return
}

// LineCount represents the imported method "line-count".
//
// Text ending with a line break has an empty last line.
//
//	line-count: func() -> u64
//
//go:nosplit
func (self Buffer) LineCount() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_BufferLineCount((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// LineOf represents the imported method "line-of".
//
//	line-of: func(pos: offset) -> result<u64, error>
//
//go:nosplit
func (self Buffer) LineOf(pos Offset) (result cm.Result[ErrorShape, uint64, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0 := (uint64)(pos)
	wasmimport_BufferLineOf((uint32)(self0), (uint64)(pos0), &result)
	return
}

// LineStart represents the imported method "line-start".
//
//	line-start: func(line: u64) -> option<offset>
//
//go:nosplit
func (self Buffer) LineStart(line uint64) (result cm.Option[Offset]) {
	self0 := cm.Reinterpret[uint32](self)
	line0 := (uint64)(line)
	wasmimport_BufferLineStart((uint32)(self0), (uint64)(line0), &result)
	return
}

// Marks represents the imported method "marks".
//
// The positions this plugin keeps in `namespace`, in the order set.
//
//	marks: func(namespace: string) -> list<offset>
//
//go:nosplit
func (self Buffer) Marks(namespace string) (result cm.List[Offset]) {
	self0 := cm.Reinterpret[uint32](self)
	namespace0, namespace1 := cm.LowerString(namespace)
	wasmimport_BufferMarks((uint32)(self0), (*uint8)(namespace0), (uint32)(namespace1), &result)
	return
}

// Modified represents the imported method "modified".
//
// Changed since it was last saved or opened. Undoing back to that
// state makes it unchanged again.
//
//	modified: func() -> bool
//
//go:nosplit
func (self Buffer) Modified() (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_BufferModified((uint32)(self0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// NextGrapheme represents the imported method "next-grapheme".
//
//	next-grapheme: func(pos: offset) -> result<offset, error>
//
//go:nosplit
func (self Buffer) NextGrapheme(pos Offset) (result cm.Result[ErrorShape, Offset, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0 := (uint64)(pos)
	wasmimport_BufferNextGrapheme((uint32)(self0), (uint64)(pos0), &result)
	return
}

// Path represents the imported method "path".
//
//	path: func() -> option<string>
//
//go:nosplit
func (self Buffer) Path() (result cm.Option[string]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_BufferPath((uint32)(self0), &result)
	return
}

// PrevGrapheme represents the imported method "prev-grapheme".
//
//	prev-grapheme: func(pos: offset) -> result<offset, error>
//
//go:nosplit
func (self Buffer) PrevGrapheme(pos Offset) (result cm.Result[ErrorShape, Offset, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0 := (uint64)(pos)
	wasmimport_BufferPrevGrapheme((uint32)(self0), (uint64)(pos0), &result)
	return
}

// Save represents the imported method "save".
//
// Saves it, or with `path`, saves it there and makes that its path.
//
//	save: func(path: option<string>) -> result<_, string>
//
//go:nosplit
func (self Buffer) Save(path cm.Option[string]) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1, path2 := lower_OptionString(path)
	wasmimport_BufferSave((uint32)(self0), (uint32)(path0), (*uint8)(path1), (uint32)(path2), &result)
	return
}

// SetMarks represents the imported method "set-marks".
//
// Replaces the positions this plugin keeps in `namespace` of this
// buffer, such as vim's marks or Emacs's mark ring; an empty list
// removes them. The core moves them with every edit, whoever makes
// it: they stay before text inserted where they are, and go where
// deleted text was. Positions past the end go to the end.
//
//	set-marks: func(namespace: string, marks: list<offset>)
//
//go:nosplit
func (self Buffer) SetMarks(namespace string, marks cm.List[Offset]) {
	self0 := cm.Reinterpret[uint32](self)
	namespace0, namespace1 := cm.LowerString(namespace)
	marks0, marks1 := cm.LowerList(marks)
	wasmimport_BufferSetMarks((uint32)(self0), (*uint8)(namespace0), (uint32)(namespace1), (*Offset)(marks0), (uint32)(marks1))
	return
}

// Slice represents the imported method "slice".
//
//	slice: func(start: offset, end: offset) -> result<string, error>
//
//go:nosplit
func (self Buffer) Slice(start Offset, end Offset) (result cm.Result[ErrorShape, string, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	start0 := (uint64)(start)
	end0 := (uint64)(end)
	wasmimport_BufferSlice((uint32)(self0), (uint64)(start0), (uint64)(end0), &result)
	return
}

// Version represents the imported method "version".
//
// Increases on every change, including undo and redo.
//
//	version: func() -> u64
//
//go:nosplit
func (self Buffer) Version() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_BufferVersion((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// Open represents the imported function "open".
//
// Opens a file, or finds the buffer that has it open, without showing
// it.
//
//	open: func(path: string) -> result<buffer, string>
//
//go:nosplit
func Open(path string) (result cm.Result[string, Buffer, string]) {
	path0, path1 := cm.LowerString(path)
	wasmimport_Open((*uint8)(path0), (uint32)(path1), &result)
	return
}

// All represents the imported function "all".
//
// Every open buffer, e.g. for a plugin enabled after files were opened.
//
//	all: func() -> list<buffer>
//
//go:nosplit
func All() (result cm.List[Buffer]) {
	wasmimport_All(&result)
	return
}
