// Code generated by wit-bindgen-go. DO NOT EDIT.

package buffer

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.6.0".

//go:wasmimport nib:plugin/buffer@0.6.0 [resource-drop]buffer
//go:noescape
func wasmimport_BufferResourceDrop(self0 uint32)

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.close
//go:noescape
func wasmimport_BufferClose(self0 uint32, force0 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.find
//go:noescape
func wasmimport_BufferFind(self0 uint32, pattern0 *uint8, pattern1 uint32, start0 uint64, backward0 uint32, result *cm.Result[OptionRangeShape, cm.Option[Range], Error])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.find-all
//go:noescape
func wasmimport_BufferFindAll(self0 uint32, pattern0 *uint8, pattern1 uint32, start0 uint64, end0 uint64, result *cm.Result[ErrorShape, cm.List[Range], Error])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.find-groups
//go:noescape
func wasmimport_BufferFindGroups(self0 uint32, pattern0 *uint8, pattern1 uint32, start0 uint64, backward0 uint32, result *cm.Result[OptionListOptionRangeShape, cm.Option[cm.List[cm.Option[Range]]], Error])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.len
//go:noescape
func wasmimport_BufferLen(self0 uint32) (result0 uint64)

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.line-count
//go:noescape
func wasmimport_BufferLineCount(self0 uint32) (result0 uint64)

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.line-of
//go:noescape
func wasmimport_BufferLineOf(self0 uint32, pos0 uint64, result *cm.Result[ErrorShape, uint64, Error])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.line-start
//go:noescape
func wasmimport_BufferLineStart(self0 uint32, line0 uint64, result *cm.Option[Offset])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.marks
//go:noescape
func wasmimport_BufferMarks(self0 uint32, namespace0 *uint8, namespace1 uint32, result *cm.List[Offset])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.modified
//go:noescape
func wasmimport_BufferModified(self0 uint32) (result0 uint32)

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.next-grapheme
//go:noescape
func wasmimport_BufferNextGrapheme(self0 uint32, pos0 uint64, result *cm.Result[ErrorShape, Offset, Error])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.path
//go:noescape
func wasmimport_BufferPath(self0 uint32, result *cm.Option[string])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.prev-grapheme
//go:noescape
func wasmimport_BufferPrevGrapheme(self0 uint32, pos0 uint64, result *cm.Result[ErrorShape, Offset, Error])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.save
//go:noescape
func wasmimport_BufferSave(self0 uint32, path0 uint32, path1 *uint8, path2 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.set-marks
//go:noescape
func wasmimport_BufferSetMarks(self0 uint32, namespace0 *uint8, namespace1 uint32, marks0 *Offset, marks1 uint32)

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.slice
//go:noescape
func wasmimport_BufferSlice(self0 uint32, start0 uint64, end0 uint64, result *cm.Result[ErrorShape, string, Error])

//go:wasmimport nib:plugin/buffer@0.6.0 [method]buffer.version
//go:noescape
func wasmimport_BufferVersion(self0 uint32) (result0 uint64)

//go:wasmimport nib:plugin/buffer@0.6.0 open
//go:noescape
func wasmimport_Open(path0 *uint8, path1 uint32, result *cm.Result[string, Buffer, string])

//go:wasmimport nib:plugin/buffer@0.6.0 all
//go:noescape
func wasmimport_All(result *cm.List[Buffer])
