// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package input represents the imported interface "nib:plugin/input@0.7.2".
package input

import (
	"go.bytecodealliance.org/cm"
)

// LeaderKey represents the record "nib:plugin/input@0.7.2#leader-key".
//
// A key a plugin's manifest suggests for one of its commands, under
// the base's leader. `keys` is written as settings write keys, such as
// "w" or "c d".
//
//	record leader-key {
//		plugin: string,
//		keys: string,
//		command: string,
//	}
type LeaderKey struct {
	_       cm.HostLayout `json:"-"`
	Plugin  string        `json:"plugin"`
	Keys    string        `json:"keys"`
	Command string        `json:"command"`
}

// Mode represents the record "nib:plugin/input@0.7.2#mode".
//
// The base's state: the base, its name for the mode ("normal",
// "insert"; "global" for bases without modes), and whether plain chars
// go into the text.
//
//	record mode {
//		base: string,
//		name: string,
//		typing: bool,
//	}
type Mode struct {
	_      cm.HostLayout `json:"-"`
	Base   string        `json:"base"`
	Name   string        `json:"name"`
	Typing bool          `json:"typing"`
}

// PushLayer represents the imported function "push-layer".
//
// Adds a layer for this plugin on top of the input stack. Keys go to the
// top layer first.
//
//	push-layer: func()
//
//go:nosplit
func PushLayer() {
	wasmimport_PushLayer()
	return
}

// PopLayer represents the imported function "pop-layer".
//
// Removes this plugin's topmost layer.
//
//	pop-layer: func()
//
//go:nosplit
func PopLayer() {
	wasmimport_PopLayer()
	return
}

// LeaderKeys represents the imported function "leader-keys".
//
// For the base: the keys enabled plugins suggest, in the order they
// were loaded.
//
//	leader-keys: func() -> list<leader-key>
//
//go:nosplit
func LeaderKeys() (result cm.List[LeaderKey]) {
	wasmimport_LeaderKeys(&result)
	return
}

// SetMode represents the imported function "set-mode".
//
// For the base: says what mode it is in; others get `mode-changed`.
// Calls from plugins that are not the running base do nothing.
//
//	set-mode: func(name: string, typing: bool)
//
//go:nosplit
func SetMode(name string, typing bool) {
	name0, name1 := cm.LowerString(name)
	typing0 := (uint32)(cm.BoolToU32(typing))
	wasmimport_SetMode((*uint8)(name0), (uint32)(name1), (uint32)(typing0))
	return
}

// CurrentMode represents the imported function "current-mode".
//
//	current-mode: func() -> mode
//
//go:nosplit
func CurrentMode() (result Mode) {
	wasmimport_CurrentMode(&result)
	return
}
