// Code generated by wit-bindgen-go. DO NOT EDIT.

package input

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.5.0".

//go:wasmimport nib:plugin/input@0.5.0 push-layer
//go:noescape
func wasmimport_PushLayer()

//go:wasmimport nib:plugin/input@0.5.0 pop-layer
//go:noescape
func wasmimport_PopLayer()
