// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package input represents the imported interface "nib:plugin/input@0.5.1".
package input

// PushLayer represents the imported function "push-layer".
//
// Adds a layer for this plugin on top of the input stack. Keys go to the
// top layer first.
//
//	push-layer: func()
//
//go:nosplit
func PushLayer() {
	wasmimport_PushLayer()
	return
}

// PopLayer represents the imported function "pop-layer".
//
// Removes this plugin's topmost layer.
//
//	pop-layer: func()
//
//go:nosplit
func PopLayer() {
	wasmimport_PopLayer()
	return
}
