// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package input represents the imported interface "nib:plugin/input@0.5.2".
package input

import (
	"go.bytecodealliance.org/cm"
)

// LeaderKey represents the record "nib:plugin/input@0.5.2#leader-key".
//
// A key a plugin's manifest suggests for one of its commands, under
// the base's leader. `keys` is written as settings write keys, such as
// "w" or "c d".
//
//	record leader-key {
//		plugin: string,
//		keys: string,
//		command: string,
//	}
type LeaderKey struct {
	_       cm.HostLayout `json:"-"`
	Plugin  string        `json:"plugin"`
	Keys    string        `json:"keys"`
	Command string        `json:"command"`
}

// PushLayer represents the imported function "push-layer".
//
// Adds a layer for this plugin on top of the input stack. Keys go to the
// top layer first.
//
//	push-layer: func()
//
//go:nosplit
func PushLayer() {
	wasmimport_PushLayer()
	return
}

// PopLayer represents the imported function "pop-layer".
//
// Removes this plugin's topmost layer.
//
//	pop-layer: func()
//
//go:nosplit
func PopLayer() {
	wasmimport_PopLayer()
	return
}

// LeaderKeys represents the imported function "leader-keys".
//
// For the base: the keys enabled plugins suggest, in the order they
// were loaded.
//
//	leader-keys: func() -> list<leader-key>
//
//go:nosplit
func LeaderKeys() (result cm.List[LeaderKey]) {
	wasmimport_LeaderKeys(&result)
	return
}
