// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package syntax represents the imported interface "nib:plugin/syntax@0.7.2".
//
// The syntax trees the core keeps for buffers with a language. Every
// function brings the buffer's tree up to date first, so it reflects edits
// made earlier in the same call. Buffers without a tree give `none` or an
// empty list.
package syntax

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/buffer"
	"github.com/nib-editor/nib/sdk/go/nib/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Offset represents the type alias "nib:plugin/syntax@0.7.2#offset".
//
// See [types.Offset] for more information.
type Offset = types.Offset

// Range represents the type alias "nib:plugin/syntax@0.7.2#range".
//
// See [types.Range] for more information.
type Range = types.Range

// Buffer represents the imported type alias "nib:plugin/syntax@0.7.2#buffer".
//
// See [buffer.Buffer] for more information.
type Buffer = buffer.Buffer

// Node represents the record "nib:plugin/syntax@0.7.2#node".
//
// A node of a buffer's syntax tree, as it was when returned. Nodes are
// values: `parent` and `children` find them again by `id` and range,
// and after the buffer changes they may no longer find them.
//
//	record node {
//		id: u64,
//		kind: string,
//		named: bool,
//		start: offset,
//		end: offset,
//	}
type Node struct {
	_ cm.HostLayout `json:"-"`
	// Tells apart nodes with the same range, e.g. an expression
	// statement and the call it consists of.
	ID uint64 `json:"id"`

	// The grammar's name for it, e.g. "function_item" or "(".
	Kind string `json:"kind"`

	// False for punctuation and keywords, which grammars name by their
	// text.
	Named bool   `json:"named"`
	Start Offset `json:"start"`
	End   Offset `json:"end"`
}

// Language represents the imported function "language".
//
// The name of the buffer's language.
//
//	language: func(buf: borrow<buffer>) -> option<string>
//
//go:nosplit
func Language(buf Buffer) (result cm.Option[string]) {
	buf0 := cm.Reinterpret[uint32](buf)
	wasmimport_Language((uint32)(buf0), &result)
	return
}

// NodeAt represents the imported function "node-at".
//
// The smallest node covering `start..end`, or with `named`, the
// smallest named one.
//
//	node-at: func(buf: borrow<buffer>, start: offset, end: offset, named: bool) ->
//	option<node>
//
//go:nosplit
func NodeAt(buf Buffer, start Offset, end Offset, named bool) (result cm.Option[Node]) {
	buf0 := cm.Reinterpret[uint32](buf)
	start0 := (uint64)(start)
	end0 := (uint64)(end)
	named0 := (uint32)(cm.BoolToU32(named))
	wasmimport_NodeAt((uint32)(buf0), (uint64)(start0), (uint64)(end0), (uint32)(named0), &result)
	return
}

// Parent represents the imported function "parent".
//
//	parent: func(buf: borrow<buffer>, of: node) -> option<node>
//
//go:nosplit
func Parent(buf Buffer, of Node) (result cm.Option[Node]) {
	buf0 := cm.Reinterpret[uint32](buf)
	of0, of1, of2, of3, of4, of5 := lower_Node(of)
	wasmimport_Parent((uint32)(buf0), (uint64)(of0), (*uint8)(of1), (uint32)(of2), (uint32)(of3), (uint64)(of4), (uint64)(of5), &result)
	return
}

// Children represents the imported function "children".
//
// All children in order, named or not.
//
//	children: func(buf: borrow<buffer>, of: node) -> list<node>
//
//go:nosplit
func Children(buf Buffer, of Node) (result cm.List[Node]) {
	buf0 := cm.Reinterpret[uint32](buf)
	of0, of1, of2, of3, of4, of5 := lower_Node(of)
	wasmimport_Children((uint32)(buf0), (uint64)(of0), (*uint8)(of1), (uint32)(of2), (uint32)(of3), (uint64)(of4), (uint64)(of5), &result)
	return
}

// Captures represents the imported function "captures".
//
// Runs the language's query named `query`, e.g. "textobjects", over
// `start..end`, and returns where `capture` matched, in order. When one
// match captures several nodes under that name, as with
// `(line_comment)+ @comment.around`, they make one range from the first
// to the last. Each range appears once. Empty when the language has no
// such query.
//
//	captures: func(buf: borrow<buffer>, query: string, capture: string, start: offset,
//	end: offset) -> list<range>
//
//go:nosplit
func Captures(buf Buffer, query string, capture string, start Offset, end Offset) (result cm.List[Range]) {
	buf0 := cm.Reinterpret[uint32](buf)
	query0, query1 := cm.LowerString(query)
	capture0, capture1 := cm.LowerString(capture)
	start0 := (uint64)(start)
	end0 := (uint64)(end)
	wasmimport_Captures((uint32)(buf0), (*uint8)(query0), (uint32)(query1), (*uint8)(capture0), (uint32)(capture1), (uint64)(start0), (uint64)(end0), &result)
	return
}
