// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package guest represents the exported interface "nib:plugin/guest@0.6.0".
package guest

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/events"
	"github.com/nib-editor/nib/sdk/go/nib/plugin/types"
	"go.bytecodealliance.org/cm"
)

// KeyEvent represents the type alias "nib:plugin/guest@0.6.0#key-event".
//
// See [types.KeyEvent] for more information.
type KeyEvent = types.KeyEvent

// Event represents the exported type alias "nib:plugin/guest@0.6.0#event".
//
// See [events.Event] for more information.
type Event = events.Event

// KeyResult represents the enum "nib:plugin/guest@0.6.0#key-result".
//
//	enum key-result {
//		handled,
//		pass
//	}
type KeyResult uint8

const (
	KeyResultHandled KeyResult = iota

	// Let the layer below handle the key.
	KeyResultPass
)

var _KeyResultStrings = [2]string{
	"handled",
	"pass",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e KeyResult) String() string {
	return _KeyResultStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e KeyResult) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *KeyResult) UnmarshalText(text []byte) error {
	return _KeyResultUnmarshalCase(e, text)
}

var _KeyResultUnmarshalCase = cm.CaseUnmarshaler[KeyResult](_KeyResultStrings[:])
