// Code generated by wit-bindgen-go. DO NOT EDIT.

package guest

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "nib:plugin/guest@0.5.2".
var Exports struct {
	// Init represents the caller-defined, exported function "init".
	//
	// Called once after loading. `config` is the plugin's config table as JSON.
	//
	//	init: func(config: string) -> result<_, string>
	Init func(config string) (result cm.Result[string, struct{}, string])

	// HandleKey represents the caller-defined, exported function "handle-key".
	//
	// A key reached one of this plugin's input layers. The core's menu key
	// (Ctrl-g by default) never arrives.
	//
	//	handle-key: func(ev: key-event) -> key-result
	HandleKey func(ev KeyEvent) (result KeyResult)

	// RunCommand represents the caller-defined, exported function "run-command".
	//
	// One of this plugin's registered commands was called, by the name it
	// was registered with.
	//
	//	run-command: func(name: string, args: string) -> result<string, string>
	RunCommand func(name string, args string) (result cm.Result[string, string, string])

	// OnEvent represents the caller-defined, exported function "on-event".
	//
	//	on-event: func(ev: event)
	OnEvent func(ev Event)
}
