// Code generated by wit-bindgen-go. DO NOT EDIT.

package guest

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.7.2".

//go:wasmexport nib:plugin/guest@0.7.2#init
//export nib:plugin/guest@0.7.2#init
func wasmexport_Init(config0 *uint8, config1 uint32) (result *cm.Result[string, struct{}, string]) {
	config := cm.LiftString[string]((*uint8)(config0), (uint32)(config1))
	result_ := Exports.Init(config)
	result = &result_
	return
}

//go:wasmexport nib:plugin/guest@0.7.2#handle-key
//export nib:plugin/guest@0.7.2#handle-key
func wasmexport_HandleKey(ev0 uint32, ev1 uint32, ev2 uint32) (result0 uint32) {
	ev := lift_KeyEvent((uint32)(ev0), (uint32)(ev1), (uint32)(ev2))
	result := Exports.HandleKey(ev)
	result0 = (uint32)(result)
	return
}

//go:wasmexport nib:plugin/guest@0.7.2#handle-paste
//export nib:plugin/guest@0.7.2#handle-paste
func wasmexport_HandlePaste(text0 *uint8, text1 uint32) (result0 uint32) {
	text := cm.LiftString[string]((*uint8)(text0), (uint32)(text1))
	result := Exports.HandlePaste(text)
	result0 = (uint32)(result)
	return
}

//go:wasmexport nib:plugin/guest@0.7.2#run-command
//export nib:plugin/guest@0.7.2#run-command
func wasmexport_RunCommand(name0 *uint8, name1 uint32, args0 *uint8, args1 uint32) (result *cm.Result[string, string, string]) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	args := cm.LiftString[string]((*uint8)(args0), (uint32)(args1))
	result_ := Exports.RunCommand(name, args)
	result = &result_
	return
}

//go:wasmexport nib:plugin/guest@0.7.2#on-event
//export nib:plugin/guest@0.7.2#on-event
func wasmexport_OnEvent(ev0 uint32, ev1 uint64, ev2 uint64, ev3 uint32, ev4 uint32, ev5 uint32) {
	ev := lift_Event((uint32)(ev0), (uint64)(ev1), (uint64)(ev2), (uint32)(ev3), (uint32)(ev4), (uint32)(ev5))
	Exports.OnEvent(ev)
	return
}
