// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package process represents the imported interface "nib:plugin/process@0.5.0".
//
// Other programs, for plugins with the "process" capability. Output is
// read on background threads and arrives as events, so plugins never wait
// for it.
package process

import (
	"go.bytecodealliance.org/cm"
)

// Stream represents the enum "nib:plugin/process@0.5.0#stream".
//
//	enum %stream {
//		stdout,
//		stderr
//	}
type Stream uint8

const (
	StreamStdout Stream = iota
	StreamStderr
)

var _StreamStrings = [2]string{
	"stdout",
	"stderr",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Stream) String() string {
	return _StreamStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Stream) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Stream) UnmarshalText(text []byte) error {
	return _StreamUnmarshalCase(e, text)
}

var _StreamUnmarshalCase = cm.CaseUnmarshaler[Stream](_StreamStrings[:])

// Child represents the imported resource "nib:plugin/process@0.5.0#child".
//
// A running program. Dropping it kills the program.
//
//	resource child
type Child cm.Resource

// ResourceDrop represents the imported resource-drop for resource "child".
//
// Drops a resource handle.
//
//go:nosplit
func (self Child) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ChildResourceDrop((uint32)(self0))
	return
}

// CloseStdin represents the imported method "close-stdin".
//
//	close-stdin: func()
//
//go:nosplit
func (self Child) CloseStdin() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ChildCloseStdin((uint32)(self0))
	return
}

// ID represents the imported method "id".
//
// The id its events carry.
//
//	id: func() -> u64
//
//go:nosplit
func (self Child) ID() (result uint64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ChildID((uint32)(self0))
	result = (uint64)((uint64)(result0))
	return
}

// Kill represents the imported method "kill".
//
//	kill: func()
//
//go:nosplit
func (self Child) Kill() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ChildKill((uint32)(self0))
	return
}

// Write represents the imported method "write".
//
// Writes to its standard input. A program that does not read can
// make this wait, so write in pieces it answers.
//
//	write: func(data: list<u8>) -> result<_, string>
//
//go:nosplit
func (self Child) Write(data cm.List[uint8]) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	data0, data1 := cm.LowerList(data)
	wasmimport_ChildWrite((uint32)(self0), (*uint8)(data0), (uint32)(data1), &result)
	return
}

// Spawn represents the imported function "spawn".
//
// Starts `command` with `args`, in `cwd` or the editor's working
// directory.
//
//	spawn: func(command: string, args: list<string>, cwd: option<string>) -> result<child,
//	string>
//
//go:nosplit
func Spawn(command string, args cm.List[string], cwd cm.Option[string]) (result cm.Result[string, Child, string]) {
	command0, command1 := cm.LowerString(command)
	args0, args1 := cm.LowerList(args)
	cwd0, cwd1, cwd2 := lower_OptionString(cwd)
	wasmimport_Spawn((*uint8)(command0), (uint32)(command1), (*string)(args0), (uint32)(args1), (uint32)(cwd0), (*uint8)(cwd1), (uint32)(cwd2), &result)
	return
}
