// Code generated by wit-bindgen-go. DO NOT EDIT.

package events

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.5.2".

//go:wasmimport nib:plugin/events@0.5.2 emit
//go:noescape
func wasmimport_Emit(name0 *uint8, name1 uint32, data0 *uint8, data1 uint32)
