// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package events represents the imported interface "nib:plugin/events@0.5.1".
//
// Events reach `guest.on-event` after the call that caused them, in the
// order they happened. A plugin gets the kinds listed in `events` in its
// plugin.toml, and its own timers and programs.
package events

import (
	"github.com/nib-editor/nib/sdk/go/nib/plugin/editor"
	"github.com/nib-editor/nib/sdk/go/nib/plugin/process"
	"github.com/nib-editor/nib/sdk/go/nib/plugin/prompt"
	"github.com/nib-editor/nib/sdk/go/nib/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Offset represents the type alias "nib:plugin/events@0.5.1#offset".
//
// See [types.Offset] for more information.
type Offset = types.Offset

// Buffer represents the imported type alias "nib:plugin/events@0.5.1#buffer".
//
// See [editor.Buffer] for more information.
type Buffer = editor.Buffer

// Stream represents the type alias "nib:plugin/events@0.5.1#stream".
//
// See [process.Stream] for more information.
type Stream = process.Stream

// Action represents the type alias "nib:plugin/events@0.5.1#action".
//
// See [prompt.Action] for more information.
type Action = prompt.Action

// TextChange represents the record "nib:plugin/events@0.5.1#text-change".
//
// One change, at positions in the text as it is when the changes
// before it in the list have been applied. Lines and columns count
// from 0; columns are in bytes.
//
//	record text-change {
//		start: offset,
//		end: offset,
//		start-line: u32,
//		start-column: u32,
//		end-line: u32,
//		end-column: u32,
//		text: string,
//	}
type TextChange struct {
	_           cm.HostLayout `json:"-"`
	Start       Offset        `json:"start"`
	End         Offset        `json:"end"`
	StartLine   uint32        `json:"start-line"`
	StartColumn uint32        `json:"start-column"`
	EndLine     uint32        `json:"end-line"`
	EndColumn   uint32        `json:"end-column"`
	Text        string        `json:"text"`
}

// BufferChange represents the imported record "nib:plugin/events@0.5.1#buffer-change".
//
// Applying `changes` in order turns the text before into the text at
// `version`, as LSP's `didChange` does.
//
//	record buffer-change {
//		buffer: buffer,
//		version: u64,
//		changes: list<text-change>,
//	}
type BufferChange struct {
	_       cm.HostLayout       `json:"-"`
	Buffer  Buffer              `json:"buffer"`
	Version uint64              `json:"version"`
	Changes cm.List[TextChange] `json:"changes"`
}

// CustomEvent represents the record "nib:plugin/events@0.5.1#custom-event".
//
// An event a plugin emitted; `name` has the plugin's name in front.
//
//	record custom-event {
//		name: string,
//		data: string,
//	}
type CustomEvent struct {
	_    cm.HostLayout `json:"-"`
	Name string        `json:"name"`
	Data string        `json:"data"`
}

// ProcessOutput represents the record "nib:plugin/events@0.5.1#process-output".
//
// Output as it was read, not split into lines.
//
//	record process-output {
//		process: u64,
//		%stream: %stream,
//		data: list<u8>,
//	}
type ProcessOutput struct {
	_       cm.HostLayout  `json:"-"`
	Process uint64         `json:"process"`
	Stream  Stream         `json:"stream"`
	Data    cm.List[uint8] `json:"data"`
}

// ProcessExit represents the record "nib:plugin/events@0.5.1#process-exit".
//
// `code` is missing when the program had none, e.g. when a signal
// ended it.
//
//	record process-exit {
//		process: u64,
//		code: option<s32>,
//	}
type ProcessExit struct {
	_       cm.HostLayout    `json:"-"`
	Process uint64           `json:"process"`
	Code    cm.Option[int32] `json:"code"`
}

// FilesListed represents the record "nib:plugin/events@0.5.1#files-listed".
//
// Up to a thousand paths of a `files.walk` job; the last ones have
// `done`.
//
//	record files-listed {
//		job: u64,
//		paths: list<string>,
//		done: bool,
//	}
type FilesListed struct {
	_     cm.HostLayout   `json:"-"`
	Job   uint64          `json:"job"`
	Paths cm.List[string] `json:"paths"`
	Done  bool            `json:"done"`
}

// PromptChange represents the record "nib:plugin/events@0.5.1#prompt-change".
//
// A prompt's text after the base edited it; `cursor` is a byte offset
// into `text`.
//
//	record prompt-change {
//		id: u64,
//		text: string,
//		cursor: u32,
//	}
type PromptChange struct {
	_      cm.HostLayout `json:"-"`
	ID     uint64        `json:"id"`
	Text   string        `json:"text"`
	Cursor uint32        `json:"cursor"`
}

// PromptAct represents the record "nib:plugin/events@0.5.1#prompt-act".
//
// What a key asked of a prompt, besides editing it.
//
//	record prompt-act {
//		id: u64,
//		action: action,
//	}
type PromptAct struct {
	_      cm.HostLayout `json:"-"`
	ID     uint64        `json:"id"`
	Action Action        `json:"action"`
}

// Event represents the imported variant "nib:plugin/events@0.5.1#event".
//
//	variant event {
//		buffer-opened(buffer),
//		buffer-saved(buffer),
//		buffer-changed(buffer-change),
//		custom(custom-event),
//		timer(u64),
//		process-output(process-output),
//		process-exit(process-exit),
//		files-listed(files-listed),
//		prompt-changed(prompt-change),
//		prompt-action(prompt-act),
//	}
type Event cm.Variant[uint8, BufferChangeShape, BufferChange]

// EventBufferOpened returns a [Event] of case "buffer-opened".
func EventBufferOpened(data Buffer) Event {
	return cm.New[Event](0, data)
}

// BufferOpened returns a non-nil *[Buffer] if [Event] represents the variant case "buffer-opened".
func (self *Event) BufferOpened() *Buffer {
	return cm.Case[Buffer](self, 0)
}

// EventBufferSaved returns a [Event] of case "buffer-saved".
func EventBufferSaved(data Buffer) Event {
	return cm.New[Event](1, data)
}

// BufferSaved returns a non-nil *[Buffer] if [Event] represents the variant case "buffer-saved".
func (self *Event) BufferSaved() *Buffer {
	return cm.Case[Buffer](self, 1)
}

// EventBufferChanged returns a [Event] of case "buffer-changed".
func EventBufferChanged(data BufferChange) Event {
	return cm.New[Event](2, data)
}

// BufferChanged returns a non-nil *[BufferChange] if [Event] represents the variant case "buffer-changed".
func (self *Event) BufferChanged() *BufferChange {
	return cm.Case[BufferChange](self, 2)
}

// EventCustom returns a [Event] of case "custom".
func EventCustom(data CustomEvent) Event {
	return cm.New[Event](3, data)
}

// Custom returns a non-nil *[CustomEvent] if [Event] represents the variant case "custom".
func (self *Event) Custom() *CustomEvent {
	return cm.Case[CustomEvent](self, 3)
}

// EventTimer returns a [Event] of case "timer".
//
// The id `timers.set` returned.
func EventTimer(data uint64) Event {
	return cm.New[Event](4, data)
}

// Timer returns a non-nil *[uint64] if [Event] represents the variant case "timer".
func (self *Event) Timer() *uint64 {
	return cm.Case[uint64](self, 4)
}

// EventProcessOutput returns a [Event] of case "process-output".
//
// Only to the plugin that started the program.
func EventProcessOutput(data ProcessOutput) Event {
	return cm.New[Event](5, data)
}

// ProcessOutput returns a non-nil *[ProcessOutput] if [Event] represents the variant case "process-output".
func (self *Event) ProcessOutput() *ProcessOutput {
	return cm.Case[ProcessOutput](self, 5)
}

// EventProcessExit returns a [Event] of case "process-exit".
func EventProcessExit(data ProcessExit) Event {
	return cm.New[Event](6, data)
}

// ProcessExit returns a non-nil *[ProcessExit] if [Event] represents the variant case "process-exit".
func (self *Event) ProcessExit() *ProcessExit {
	return cm.Case[ProcessExit](self, 6)
}

// EventFilesListed returns a [Event] of case "files-listed".
//
// Only to the plugin that asked for the list.
func EventFilesListed(data FilesListed) Event {
	return cm.New[Event](7, data)
}

// FilesListed returns a non-nil *[FilesListed] if [Event] represents the variant case "files-listed".
func (self *Event) FilesListed() *FilesListed {
	return cm.Case[FilesListed](self, 7)
}

// EventPromptChanged returns a [Event] of case "prompt-changed".
//
// Only to the plugin that opened the prompt.
func EventPromptChanged(data PromptChange) Event {
	return cm.New[Event](8, data)
}

// PromptChanged returns a non-nil *[PromptChange] if [Event] represents the variant case "prompt-changed".
func (self *Event) PromptChanged() *PromptChange {
	return cm.Case[PromptChange](self, 8)
}

// EventPromptAction returns a [Event] of case "prompt-action".
func EventPromptAction(data PromptAct) Event {
	return cm.New[Event](9, data)
}

// PromptAction returns a non-nil *[PromptAct] if [Event] represents the variant case "prompt-action".
func (self *Event) PromptAction() *PromptAct {
	return cm.Case[PromptAct](self, 9)
}

var _EventStrings = [10]string{
	"buffer-opened",
	"buffer-saved",
	"buffer-changed",
	"custom",
	"timer",
	"process-output",
	"process-exit",
	"files-listed",
	"prompt-changed",
	"prompt-action",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Event) String() string {
	return _EventStrings[v.Tag()]
}

// Emit represents the imported function "emit".
//
// Emits the custom event `<plugin>.<name>` with JSON `data`.
//
//	emit: func(name: string, data: string)
//
//go:nosplit
func Emit(name string, data string) {
	name0, name1 := cm.LowerString(name)
	data0, data1 := cm.LowerString(data)
	wasmimport_Emit((*uint8)(name0), (uint32)(name1), (*uint8)(data0), (uint32)(data1))
	return
}
