// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "nib:plugin/types@0.6.0".
package types

import (
	"go.bytecodealliance.org/cm"
)

// Offset represents the u64 "nib:plugin/types@0.6.0#offset".
//
// A UTF-8 byte offset into a buffer.
//
//	type offset = u64
type Offset uint64

// Range represents the record "nib:plugin/types@0.6.0#range".
//
// `start..end` of a buffer.
//
//	record range {
//		start: offset,
//		end: offset,
//	}
type Range struct {
	_     cm.HostLayout `json:"-"`
	Start Offset        `json:"start"`
	End   Offset        `json:"end"`
}

// SelRange represents the record "nib:plugin/types@0.6.0#sel-range".
//
// `head` is where the cursor is, so it may be before `anchor`.
//
//	record sel-range {
//		anchor: offset,
//		head: offset,
//	}
type SelRange struct {
	_      cm.HostLayout `json:"-"`
	Anchor Offset        `json:"anchor"`
	Head   Offset        `json:"head"`
}

// Selection represents the record "nib:plugin/types@0.6.0#selection".
//
//	record selection {
//		ranges: list<sel-range>,
//		primary: u32,
//	}
type Selection struct {
	_       cm.HostLayout     `json:"-"`
	Ranges  cm.List[SelRange] `json:"ranges"`
	Primary uint32            `json:"primary"`
}

// Edit represents the record "nib:plugin/types@0.6.0#edit".
//
// Replaces `start..end` of the buffer before the change with `text`.
//
//	record edit {
//		start: offset,
//		end: offset,
//		text: string,
//	}
type Edit struct {
	_     cm.HostLayout `json:"-"`
	Start Offset        `json:"start"`
	End   Offset        `json:"end"`
	Text  string        `json:"text"`
}

// UndoMode represents the enum "nib:plugin/types@0.6.0#undo-mode".
//
//	enum undo-mode {
//		new-step,
//		merge
//	}
type UndoMode uint8

const (
	// Start a new undo step.
	UndoModeNewStep UndoMode = iota

	// Add to the last undo step, e.g. while typing in insert mode.
	UndoModeMerge
)

var _UndoModeStrings = [2]string{
	"new-step",
	"merge",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e UndoMode) String() string {
	return _UndoModeStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e UndoMode) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *UndoMode) UnmarshalText(text []byte) error {
	return _UndoModeUnmarshalCase(e, text)
}

var _UndoModeUnmarshalCase = cm.CaseUnmarshaler[UndoMode](_UndoModeStrings[:])

// CursorShape represents the enum "nib:plugin/types@0.6.0#cursor-shape".
//
//	enum cursor-shape {
//		block,
//		bar,
//		underline
//	}
type CursorShape uint8

const (
	CursorShapeBlock CursorShape = iota
	CursorShapeBar
	CursorShapeUnderline
)

var _CursorShapeStrings = [3]string{
	"block",
	"bar",
	"underline",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e CursorShape) String() string {
	return _CursorShapeStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e CursorShape) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *CursorShape) UnmarshalText(text []byte) error {
	return _CursorShapeUnmarshalCase(e, text)
}

var _CursorShapeUnmarshalCase = cm.CaseUnmarshaler[CursorShape](_CursorShapeStrings[:])

// Modifiers represents the flags "nib:plugin/types@0.6.0#modifiers".
//
// Shift is never set for chars: 'Q' already says it is shifted.
//
//	flags modifiers {
//		ctrl,
//		alt,
//		shift,
//		super,
//	}
type Modifiers uint8

const (
	ModifiersCtrl Modifiers = 1 << iota
	ModifiersAlt
	ModifiersShift
	ModifiersSuper
)

// KeyCode represents the variant "nib:plugin/types@0.6.0#key-code".
//
//	variant key-code {
//		%char(char),
//		enter,
//		escape,
//		tab,
//		backspace,
//		delete,
//		insert,
//		up,
//		down,
//		left,
//		right,
//		home,
//		end,
//		page-up,
//		page-down,
//		f(u8),
//	}
type KeyCode cm.Variant[uint8, rune, rune]

// KeyCodeChar returns a [KeyCode] of case "char".
func KeyCodeChar(data rune) KeyCode {
	return cm.New[KeyCode](0, data)
}

// Char returns a non-nil *[rune] if [KeyCode] represents the variant case "char".
func (self *KeyCode) Char() *rune {
	return cm.Case[rune](self, 0)
}

// KeyCodeEnter returns a [KeyCode] of case "enter".
func KeyCodeEnter() KeyCode {
	var data struct{}
	return cm.New[KeyCode](1, data)
}

// Enter returns true if [KeyCode] represents the variant case "enter".
func (self *KeyCode) Enter() bool {
	return self.Tag() == 1
}

// KeyCodeEscape returns a [KeyCode] of case "escape".
func KeyCodeEscape() KeyCode {
	var data struct{}
	return cm.New[KeyCode](2, data)
}

// Escape returns true if [KeyCode] represents the variant case "escape".
func (self *KeyCode) Escape() bool {
	return self.Tag() == 2
}

// KeyCodeTab returns a [KeyCode] of case "tab".
func KeyCodeTab() KeyCode {
	var data struct{}
	return cm.New[KeyCode](3, data)
}

// Tab returns true if [KeyCode] represents the variant case "tab".
func (self *KeyCode) Tab() bool {
	return self.Tag() == 3
}

// KeyCodeBackspace returns a [KeyCode] of case "backspace".
func KeyCodeBackspace() KeyCode {
	var data struct{}
	return cm.New[KeyCode](4, data)
}

// Backspace returns true if [KeyCode] represents the variant case "backspace".
func (self *KeyCode) Backspace() bool {
	return self.Tag() == 4
}

// KeyCodeDelete returns a [KeyCode] of case "delete".
func KeyCodeDelete() KeyCode {
	var data struct{}
	return cm.New[KeyCode](5, data)
}

// Delete returns true if [KeyCode] represents the variant case "delete".
func (self *KeyCode) Delete() bool {
	return self.Tag() == 5
}

// KeyCodeInsert returns a [KeyCode] of case "insert".
func KeyCodeInsert() KeyCode {
	var data struct{}
	return cm.New[KeyCode](6, data)
}

// Insert returns true if [KeyCode] represents the variant case "insert".
func (self *KeyCode) Insert() bool {
	return self.Tag() == 6
}

// KeyCodeUp returns a [KeyCode] of case "up".
func KeyCodeUp() KeyCode {
	var data struct{}
	return cm.New[KeyCode](7, data)
}

// Up returns true if [KeyCode] represents the variant case "up".
func (self *KeyCode) Up() bool {
	return self.Tag() == 7
}

// KeyCodeDown returns a [KeyCode] of case "down".
func KeyCodeDown() KeyCode {
	var data struct{}
	return cm.New[KeyCode](8, data)
}

// Down returns true if [KeyCode] represents the variant case "down".
func (self *KeyCode) Down() bool {
	return self.Tag() == 8
}

// KeyCodeLeft returns a [KeyCode] of case "left".
func KeyCodeLeft() KeyCode {
	var data struct{}
	return cm.New[KeyCode](9, data)
}

// Left returns true if [KeyCode] represents the variant case "left".
func (self *KeyCode) Left() bool {
	return self.Tag() == 9
}

// KeyCodeRight returns a [KeyCode] of case "right".
func KeyCodeRight() KeyCode {
	var data struct{}
	return cm.New[KeyCode](10, data)
}

// Right returns true if [KeyCode] represents the variant case "right".
func (self *KeyCode) Right() bool {
	return self.Tag() == 10
}

// KeyCodeHome returns a [KeyCode] of case "home".
func KeyCodeHome() KeyCode {
	var data struct{}
	return cm.New[KeyCode](11, data)
}

// Home returns true if [KeyCode] represents the variant case "home".
func (self *KeyCode) Home() bool {
	return self.Tag() == 11
}

// KeyCodeEnd returns a [KeyCode] of case "end".
func KeyCodeEnd() KeyCode {
	var data struct{}
	return cm.New[KeyCode](12, data)
}

// End returns true if [KeyCode] represents the variant case "end".
func (self *KeyCode) End() bool {
	return self.Tag() == 12
}

// KeyCodePageUp returns a [KeyCode] of case "page-up".
func KeyCodePageUp() KeyCode {
	var data struct{}
	return cm.New[KeyCode](13, data)
}

// PageUp returns true if [KeyCode] represents the variant case "page-up".
func (self *KeyCode) PageUp() bool {
	return self.Tag() == 13
}

// KeyCodePageDown returns a [KeyCode] of case "page-down".
func KeyCodePageDown() KeyCode {
	var data struct{}
	return cm.New[KeyCode](14, data)
}

// PageDown returns true if [KeyCode] represents the variant case "page-down".
func (self *KeyCode) PageDown() bool {
	return self.Tag() == 14
}

// KeyCodeF returns a [KeyCode] of case "f".
func KeyCodeF(data uint8) KeyCode {
	return cm.New[KeyCode](15, data)
}

// F returns a non-nil *[uint8] if [KeyCode] represents the variant case "f".
func (self *KeyCode) F() *uint8 {
	return cm.Case[uint8](self, 15)
}

var _KeyCodeStrings = [16]string{
	"char",
	"enter",
	"escape",
	"tab",
	"backspace",
	"delete",
	"insert",
	"up",
	"down",
	"left",
	"right",
	"home",
	"end",
	"page-up",
	"page-down",
	"f",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v KeyCode) String() string {
	return _KeyCodeStrings[v.Tag()]
}

// KeyEvent represents the record "nib:plugin/types@0.6.0#key-event".
//
//	record key-event {
//		code: key-code,
//		modifiers: modifiers,
//	}
type KeyEvent struct {
	_         cm.HostLayout `json:"-"`
	Code      KeyCode       `json:"code"`
	Modifiers Modifiers     `json:"modifiers"`
}

// Span represents the record "nib:plugin/types@0.6.0#span".
//
// `style` names a theme entry, e.g. "ui.mode.normal".
//
//	record span {
//		text: string,
//		style: string,
//	}
type Span struct {
	_     cm.HostLayout `json:"-"`
	Text  string        `json:"text"`
	Style string        `json:"style"`
}

// StyledLine represents the list "nib:plugin/types@0.6.0#styled-line".
//
//	type styled-line = list<span>
type StyledLine cm.List[Span]

// Error represents the variant "nib:plugin/types@0.6.0#error".
//
//	variant error {
//		stale-version,
//		invalid-position,
//		overlapping-edits,
//		invalid-selection,
//		invalid-pattern(string),
//		other(string),
//	}
type Error cm.Variant[uint8, string, string]

// ErrorStaleVersion returns a [Error] of case "stale-version".
//
// The change was built against an older version of the buffer.
func ErrorStaleVersion() Error {
	var data struct{}
	return cm.New[Error](0, data)
}

// StaleVersion returns true if [Error] represents the variant case "stale-version".
func (self *Error) StaleVersion() bool {
	return self.Tag() == 0
}

// ErrorInvalidPosition returns a [Error] of case "invalid-position".
//
// The offset is out of bounds or not on a char boundary.
func ErrorInvalidPosition() Error {
	var data struct{}
	return cm.New[Error](1, data)
}

// InvalidPosition returns true if [Error] represents the variant case "invalid-position".
func (self *Error) InvalidPosition() bool {
	return self.Tag() == 1
}

// ErrorOverlappingEdits returns a [Error] of case "overlapping-edits".
//
// Edits in one change overlap each other.
func ErrorOverlappingEdits() Error {
	var data struct{}
	return cm.New[Error](2, data)
}

// OverlappingEdits returns true if [Error] represents the variant case "overlapping-edits".
func (self *Error) OverlappingEdits() bool {
	return self.Tag() == 2
}

// ErrorInvalidSelection returns a [Error] of case "invalid-selection".
//
// A selection needs at least one range and a primary index in bounds.
func ErrorInvalidSelection() Error {
	var data struct{}
	return cm.New[Error](3, data)
}

// InvalidSelection returns true if [Error] represents the variant case "invalid-selection".
func (self *Error) InvalidSelection() bool {
	return self.Tag() == 3
}

// ErrorInvalidPattern returns a [Error] of case "invalid-pattern".
func ErrorInvalidPattern(data string) Error {
	return cm.New[Error](4, data)
}

// InvalidPattern returns a non-nil *[string] if [Error] represents the variant case "invalid-pattern".
func (self *Error) InvalidPattern() *string {
	return cm.Case[string](self, 4)
}

// ErrorOther returns a [Error] of case "other".
func ErrorOther(data string) Error {
	return cm.New[Error](5, data)
}

// Other returns a non-nil *[string] if [Error] represents the variant case "other".
func (self *Error) Other() *string {
	return cm.Case[string](self, 5)
}

var _ErrorStrings = [6]string{
	"stale-version",
	"invalid-position",
	"overlapping-edits",
	"invalid-selection",
	"invalid-pattern",
	"other",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Error) String() string {
	return _ErrorStrings[v.Tag()]
}
