// Code generated by wit-bindgen-go. DO NOT EDIT.

package clipboard

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "nib:plugin@0.7.0".

//go:wasmimport nib:plugin/clipboard@0.7.0 get
//go:noescape
func wasmimport_Get(result *cm.Result[string, string, string])

//go:wasmimport nib:plugin/clipboard@0.7.0 set
//go:noescape
func wasmimport_Set(text0 *uint8, text1 uint32, result *cm.Result[string, struct{}, string])
