// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package clipboard represents the imported interface "nib:plugin/clipboard@0.5.0".
//
// The system clipboard, for plugins with the "clipboard" capability.
package clipboard

import (
	"go.bytecodealliance.org/cm"
)

// Get represents the imported function "get".
//
//	get: func() -> result<string, string>
//
//go:nosplit
func Get() (result cm.Result[string, string, string]) {
	wasmimport_Get(&result)
	return
}

// Set represents the imported function "set".
//
//	set: func(text: string) -> result<_, string>
//
//go:nosplit
func Set(text string) (result cm.Result[string, struct{}, string]) {
	text0, text1 := cm.LowerString(text)
	wasmimport_Set((*uint8)(text0), (uint32)(text1), &result)
	return
}
